// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.2
// source: user/v1/user.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationUserAssignRoles = "/api.user.v1.User/AssignRoles"
const OperationUserCreate = "/api.user.v1.User/Create"
const OperationUserDelete = "/api.user.v1.User/Delete"
const OperationUserGet = "/api.user.v1.User/Get"
const OperationUserList = "/api.user.v1.User/List"
const OperationUserResetPassword = "/api.user.v1.User/ResetPassword"
const OperationUserSetStatus = "/api.user.v1.User/SetStatus"
const OperationUserUpdate = "/api.user.v1.User/Update"

type UserHTTPServer interface {
	// AssignRoles 分配用户角色
	AssignRoles(context.Context, *UserAssignRolesRequest) (*UserAssignRolesReply, error)
	// Create 创建用户
	Create(context.Context, *UserCreateRequest) (*UserCreateReply, error)
	// Delete 删除用户
	Delete(context.Context, *UserDeleteRequest) (*UserDeleteReply, error)
	// Get 获取用户详情
	Get(context.Context, *UserGetRequest) (*UserGetReply, error)
	// List 获取用户列表
	List(context.Context, *UserListRequest) (*UserListReply, error)
	// ResetPassword 重置密码
	ResetPassword(context.Context, *UserResetPasswordRequest) (*UserResetPasswordReply, error)
	// SetStatus 设置用户状态
	SetStatus(context.Context, *UserSetStatusRequest) (*UserSetStatusReply, error)
	// Update 更新用户
	Update(context.Context, *UserUpdateRequest) (*UserUpdateReply, error)
}

func RegisterUserHTTPServer(s *http.Server, srv UserHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/user/list", _User_List2_HTTP_Handler(srv))
	r.GET("/api/v1/user/{id}", _User_Get2_HTTP_Handler(srv))
	r.POST("/api/v1/user", _User_Create2_HTTP_Handler(srv))
	r.PUT("/api/v1/user/{id}", _User_Update2_HTTP_Handler(srv))
	r.DELETE("/api/v1/user/{id}", _User_Delete2_HTTP_Handler(srv))
	r.PUT("/api/v1/user/{id}/roles", _User_AssignRoles0_HTTP_Handler(srv))
	r.PUT("/api/v1/user/{id}/status", _User_SetStatus0_HTTP_Handler(srv))
	r.PUT("/api/v1/user/{id}/reset-password", _User_ResetPassword0_HTTP_Handler(srv))
}

func _User_List2_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UserListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.List(ctx, req.(*UserListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserListReply)
		return ctx.Result(200, reply)
	}
}

func _User_Get2_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UserGetRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserGet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Get(ctx, req.(*UserGetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserGetReply)
		return ctx.Result(200, reply)
	}
}

func _User_Create2_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UserCreateRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserCreate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Create(ctx, req.(*UserCreateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserCreateReply)
		return ctx.Result(200, reply)
	}
}

func _User_Update2_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UserUpdateRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserUpdate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Update(ctx, req.(*UserUpdateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserUpdateReply)
		return ctx.Result(200, reply)
	}
}

func _User_Delete2_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UserDeleteRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserDelete)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Delete(ctx, req.(*UserDeleteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserDeleteReply)
		return ctx.Result(200, reply)
	}
}

func _User_AssignRoles0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UserAssignRolesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserAssignRoles)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AssignRoles(ctx, req.(*UserAssignRolesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserAssignRolesReply)
		return ctx.Result(200, reply)
	}
}

func _User_SetStatus0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UserSetStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserSetStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetStatus(ctx, req.(*UserSetStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserSetStatusReply)
		return ctx.Result(200, reply)
	}
}

func _User_ResetPassword0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UserResetPasswordRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserResetPassword)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ResetPassword(ctx, req.(*UserResetPasswordRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserResetPasswordReply)
		return ctx.Result(200, reply)
	}
}

type UserHTTPClient interface {
	// AssignRoles 分配用户角色
	AssignRoles(ctx context.Context, req *UserAssignRolesRequest, opts ...http.CallOption) (rsp *UserAssignRolesReply, err error)
	// Create 创建用户
	Create(ctx context.Context, req *UserCreateRequest, opts ...http.CallOption) (rsp *UserCreateReply, err error)
	// Delete 删除用户
	Delete(ctx context.Context, req *UserDeleteRequest, opts ...http.CallOption) (rsp *UserDeleteReply, err error)
	// Get 获取用户详情
	Get(ctx context.Context, req *UserGetRequest, opts ...http.CallOption) (rsp *UserGetReply, err error)
	// List 获取用户列表
	List(ctx context.Context, req *UserListRequest, opts ...http.CallOption) (rsp *UserListReply, err error)
	// ResetPassword 重置密码
	ResetPassword(ctx context.Context, req *UserResetPasswordRequest, opts ...http.CallOption) (rsp *UserResetPasswordReply, err error)
	// SetStatus 设置用户状态
	SetStatus(ctx context.Context, req *UserSetStatusRequest, opts ...http.CallOption) (rsp *UserSetStatusReply, err error)
	// Update 更新用户
	Update(ctx context.Context, req *UserUpdateRequest, opts ...http.CallOption) (rsp *UserUpdateReply, err error)
}

type UserHTTPClientImpl struct {
	cc *http.Client
}

func NewUserHTTPClient(client *http.Client) UserHTTPClient {
	return &UserHTTPClientImpl{client}
}

// AssignRoles 分配用户角色
func (c *UserHTTPClientImpl) AssignRoles(ctx context.Context, in *UserAssignRolesRequest, opts ...http.CallOption) (*UserAssignRolesReply, error) {
	var out UserAssignRolesReply
	pattern := "/api/v1/user/{id}/roles"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserAssignRoles))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Create 创建用户
func (c *UserHTTPClientImpl) Create(ctx context.Context, in *UserCreateRequest, opts ...http.CallOption) (*UserCreateReply, error) {
	var out UserCreateReply
	pattern := "/api/v1/user"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserCreate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete 删除用户
func (c *UserHTTPClientImpl) Delete(ctx context.Context, in *UserDeleteRequest, opts ...http.CallOption) (*UserDeleteReply, error) {
	var out UserDeleteReply
	pattern := "/api/v1/user/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserDelete))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Get 获取用户详情
func (c *UserHTTPClientImpl) Get(ctx context.Context, in *UserGetRequest, opts ...http.CallOption) (*UserGetReply, error) {
	var out UserGetReply
	pattern := "/api/v1/user/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserGet))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// List 获取用户列表
func (c *UserHTTPClientImpl) List(ctx context.Context, in *UserListRequest, opts ...http.CallOption) (*UserListReply, error) {
	var out UserListReply
	pattern := "/api/v1/user/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ResetPassword 重置密码
func (c *UserHTTPClientImpl) ResetPassword(ctx context.Context, in *UserResetPasswordRequest, opts ...http.CallOption) (*UserResetPasswordReply, error) {
	var out UserResetPasswordReply
	pattern := "/api/v1/user/{id}/reset-password"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserResetPassword))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SetStatus 设置用户状态
func (c *UserHTTPClientImpl) SetStatus(ctx context.Context, in *UserSetStatusRequest, opts ...http.CallOption) (*UserSetStatusReply, error) {
	var out UserSetStatusReply
	pattern := "/api/v1/user/{id}/status"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserSetStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Update 更新用户
func (c *UserHTTPClientImpl) Update(ctx context.Context, in *UserUpdateRequest, opts ...http.CallOption) (*UserUpdateReply, error) {
	var out UserUpdateReply
	pattern := "/api/v1/user/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserUpdate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
