// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/role/v1/role.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on RoleListRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RoleListRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RoleListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RoleListRequestMultiError, or nil if none found.
func (m *RoleListRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RoleListRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Code

	// no validation rules for Page

	// no validation rules for PageSize

	if len(errors) > 0 {
		return RoleListRequestMultiError(errors)
	}

	return nil
}

// RoleListRequestMultiError is an error wrapping multiple validation errors
// returned by RoleListRequest.ValidateAll() if the designated constraints
// aren't met.
type RoleListRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RoleListRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RoleListRequestMultiError) AllErrors() []error { return m }

// RoleListRequestValidationError is the validation error returned by
// RoleListRequest.Validate if the designated constraints aren't met.
type RoleListRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RoleListRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RoleListRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RoleListRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RoleListRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RoleListRequestValidationError) ErrorName() string { return "RoleListRequestValidationError" }

// Error satisfies the builtin error interface
func (e RoleListRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRoleListRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RoleListRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RoleListRequestValidationError{}

// Validate checks the field values on RoleListReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RoleListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RoleListReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RoleListReplyMultiError, or
// nil if none found.
func (m *RoleListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *RoleListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RoleListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RoleListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RoleListReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return RoleListReplyMultiError(errors)
	}

	return nil
}

// RoleListReplyMultiError is an error wrapping multiple validation errors
// returned by RoleListReply.ValidateAll() if the designated constraints
// aren't met.
type RoleListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RoleListReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RoleListReplyMultiError) AllErrors() []error { return m }

// RoleListReplyValidationError is the validation error returned by
// RoleListReply.Validate if the designated constraints aren't met.
type RoleListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RoleListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RoleListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RoleListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RoleListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RoleListReplyValidationError) ErrorName() string { return "RoleListReplyValidationError" }

// Error satisfies the builtin error interface
func (e RoleListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRoleListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RoleListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RoleListReplyValidationError{}

// Validate checks the field values on RoleGetRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RoleGetRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RoleGetRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RoleGetRequestMultiError,
// or nil if none found.
func (m *RoleGetRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RoleGetRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return RoleGetRequestMultiError(errors)
	}

	return nil
}

// RoleGetRequestMultiError is an error wrapping multiple validation errors
// returned by RoleGetRequest.ValidateAll() if the designated constraints
// aren't met.
type RoleGetRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RoleGetRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RoleGetRequestMultiError) AllErrors() []error { return m }

// RoleGetRequestValidationError is the validation error returned by
// RoleGetRequest.Validate if the designated constraints aren't met.
type RoleGetRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RoleGetRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RoleGetRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RoleGetRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RoleGetRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RoleGetRequestValidationError) ErrorName() string { return "RoleGetRequestValidationError" }

// Error satisfies the builtin error interface
func (e RoleGetRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRoleGetRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RoleGetRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RoleGetRequestValidationError{}

// Validate checks the field values on RoleGetReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RoleGetReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RoleGetReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RoleGetReplyMultiError, or
// nil if none found.
func (m *RoleGetReply) ValidateAll() error {
	return m.validate(true)
}

func (m *RoleGetReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetRole()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RoleGetReplyValidationError{
					field:  "Role",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RoleGetReplyValidationError{
					field:  "Role",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRole()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RoleGetReplyValidationError{
				field:  "Role",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return RoleGetReplyMultiError(errors)
	}

	return nil
}

// RoleGetReplyMultiError is an error wrapping multiple validation errors
// returned by RoleGetReply.ValidateAll() if the designated constraints aren't met.
type RoleGetReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RoleGetReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RoleGetReplyMultiError) AllErrors() []error { return m }

// RoleGetReplyValidationError is the validation error returned by
// RoleGetReply.Validate if the designated constraints aren't met.
type RoleGetReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RoleGetReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RoleGetReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RoleGetReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RoleGetReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RoleGetReplyValidationError) ErrorName() string { return "RoleGetReplyValidationError" }

// Error satisfies the builtin error interface
func (e RoleGetReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRoleGetReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RoleGetReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RoleGetReplyValidationError{}

// Validate checks the field values on RoleCreateRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RoleCreateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RoleCreateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RoleCreateRequestMultiError, or nil if none found.
func (m *RoleCreateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RoleCreateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Code

	if len(errors) > 0 {
		return RoleCreateRequestMultiError(errors)
	}

	return nil
}

// RoleCreateRequestMultiError is an error wrapping multiple validation errors
// returned by RoleCreateRequest.ValidateAll() if the designated constraints
// aren't met.
type RoleCreateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RoleCreateRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RoleCreateRequestMultiError) AllErrors() []error { return m }

// RoleCreateRequestValidationError is the validation error returned by
// RoleCreateRequest.Validate if the designated constraints aren't met.
type RoleCreateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RoleCreateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RoleCreateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RoleCreateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RoleCreateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RoleCreateRequestValidationError) ErrorName() string {
	return "RoleCreateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RoleCreateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRoleCreateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RoleCreateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RoleCreateRequestValidationError{}

// Validate checks the field values on RoleCreateReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RoleCreateReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RoleCreateReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RoleCreateReplyMultiError, or nil if none found.
func (m *RoleCreateReply) ValidateAll() error {
	return m.validate(true)
}

func (m *RoleCreateReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return RoleCreateReplyMultiError(errors)
	}

	return nil
}

// RoleCreateReplyMultiError is an error wrapping multiple validation errors
// returned by RoleCreateReply.ValidateAll() if the designated constraints
// aren't met.
type RoleCreateReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RoleCreateReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RoleCreateReplyMultiError) AllErrors() []error { return m }

// RoleCreateReplyValidationError is the validation error returned by
// RoleCreateReply.Validate if the designated constraints aren't met.
type RoleCreateReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RoleCreateReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RoleCreateReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RoleCreateReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RoleCreateReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RoleCreateReplyValidationError) ErrorName() string { return "RoleCreateReplyValidationError" }

// Error satisfies the builtin error interface
func (e RoleCreateReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRoleCreateReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RoleCreateReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RoleCreateReplyValidationError{}

// Validate checks the field values on RoleUpdateRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RoleUpdateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RoleUpdateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RoleUpdateRequestMultiError, or nil if none found.
func (m *RoleUpdateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RoleUpdateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Code

	if len(errors) > 0 {
		return RoleUpdateRequestMultiError(errors)
	}

	return nil
}

// RoleUpdateRequestMultiError is an error wrapping multiple validation errors
// returned by RoleUpdateRequest.ValidateAll() if the designated constraints
// aren't met.
type RoleUpdateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RoleUpdateRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RoleUpdateRequestMultiError) AllErrors() []error { return m }

// RoleUpdateRequestValidationError is the validation error returned by
// RoleUpdateRequest.Validate if the designated constraints aren't met.
type RoleUpdateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RoleUpdateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RoleUpdateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RoleUpdateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RoleUpdateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RoleUpdateRequestValidationError) ErrorName() string {
	return "RoleUpdateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RoleUpdateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRoleUpdateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RoleUpdateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RoleUpdateRequestValidationError{}

// Validate checks the field values on RoleUpdateReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RoleUpdateReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RoleUpdateReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RoleUpdateReplyMultiError, or nil if none found.
func (m *RoleUpdateReply) ValidateAll() error {
	return m.validate(true)
}

func (m *RoleUpdateReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return RoleUpdateReplyMultiError(errors)
	}

	return nil
}

// RoleUpdateReplyMultiError is an error wrapping multiple validation errors
// returned by RoleUpdateReply.ValidateAll() if the designated constraints
// aren't met.
type RoleUpdateReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RoleUpdateReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RoleUpdateReplyMultiError) AllErrors() []error { return m }

// RoleUpdateReplyValidationError is the validation error returned by
// RoleUpdateReply.Validate if the designated constraints aren't met.
type RoleUpdateReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RoleUpdateReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RoleUpdateReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RoleUpdateReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RoleUpdateReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RoleUpdateReplyValidationError) ErrorName() string { return "RoleUpdateReplyValidationError" }

// Error satisfies the builtin error interface
func (e RoleUpdateReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRoleUpdateReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RoleUpdateReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RoleUpdateReplyValidationError{}

// Validate checks the field values on RoleDeleteRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RoleDeleteRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RoleDeleteRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RoleDeleteRequestMultiError, or nil if none found.
func (m *RoleDeleteRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RoleDeleteRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return RoleDeleteRequestMultiError(errors)
	}

	return nil
}

// RoleDeleteRequestMultiError is an error wrapping multiple validation errors
// returned by RoleDeleteRequest.ValidateAll() if the designated constraints
// aren't met.
type RoleDeleteRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RoleDeleteRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RoleDeleteRequestMultiError) AllErrors() []error { return m }

// RoleDeleteRequestValidationError is the validation error returned by
// RoleDeleteRequest.Validate if the designated constraints aren't met.
type RoleDeleteRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RoleDeleteRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RoleDeleteRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RoleDeleteRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RoleDeleteRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RoleDeleteRequestValidationError) ErrorName() string {
	return "RoleDeleteRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RoleDeleteRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRoleDeleteRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RoleDeleteRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RoleDeleteRequestValidationError{}

// Validate checks the field values on RoleDeleteReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RoleDeleteReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RoleDeleteReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RoleDeleteReplyMultiError, or nil if none found.
func (m *RoleDeleteReply) ValidateAll() error {
	return m.validate(true)
}

func (m *RoleDeleteReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return RoleDeleteReplyMultiError(errors)
	}

	return nil
}

// RoleDeleteReplyMultiError is an error wrapping multiple validation errors
// returned by RoleDeleteReply.ValidateAll() if the designated constraints
// aren't met.
type RoleDeleteReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RoleDeleteReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RoleDeleteReplyMultiError) AllErrors() []error { return m }

// RoleDeleteReplyValidationError is the validation error returned by
// RoleDeleteReply.Validate if the designated constraints aren't met.
type RoleDeleteReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RoleDeleteReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RoleDeleteReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RoleDeleteReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RoleDeleteReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RoleDeleteReplyValidationError) ErrorName() string { return "RoleDeleteReplyValidationError" }

// Error satisfies the builtin error interface
func (e RoleDeleteReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRoleDeleteReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RoleDeleteReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RoleDeleteReplyValidationError{}

// Validate checks the field values on RoleAssignPermissionsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RoleAssignPermissionsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RoleAssignPermissionsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RoleAssignPermissionsRequestMultiError, or nil if none found.
func (m *RoleAssignPermissionsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RoleAssignPermissionsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for DataScope

	if len(errors) > 0 {
		return RoleAssignPermissionsRequestMultiError(errors)
	}

	return nil
}

// RoleAssignPermissionsRequestMultiError is an error wrapping multiple
// validation errors returned by RoleAssignPermissionsRequest.ValidateAll() if
// the designated constraints aren't met.
type RoleAssignPermissionsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RoleAssignPermissionsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RoleAssignPermissionsRequestMultiError) AllErrors() []error { return m }

// RoleAssignPermissionsRequestValidationError is the validation error returned
// by RoleAssignPermissionsRequest.Validate if the designated constraints
// aren't met.
type RoleAssignPermissionsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RoleAssignPermissionsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RoleAssignPermissionsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RoleAssignPermissionsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RoleAssignPermissionsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RoleAssignPermissionsRequestValidationError) ErrorName() string {
	return "RoleAssignPermissionsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RoleAssignPermissionsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRoleAssignPermissionsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RoleAssignPermissionsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RoleAssignPermissionsRequestValidationError{}

// Validate checks the field values on RoleAssignPermissionsReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RoleAssignPermissionsReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RoleAssignPermissionsReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RoleAssignPermissionsReplyMultiError, or nil if none found.
func (m *RoleAssignPermissionsReply) ValidateAll() error {
	return m.validate(true)
}

func (m *RoleAssignPermissionsReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return RoleAssignPermissionsReplyMultiError(errors)
	}

	return nil
}

// RoleAssignPermissionsReplyMultiError is an error wrapping multiple
// validation errors returned by RoleAssignPermissionsReply.ValidateAll() if
// the designated constraints aren't met.
type RoleAssignPermissionsReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RoleAssignPermissionsReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RoleAssignPermissionsReplyMultiError) AllErrors() []error { return m }

// RoleAssignPermissionsReplyValidationError is the validation error returned
// by RoleAssignPermissionsReply.Validate if the designated constraints aren't met.
type RoleAssignPermissionsReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RoleAssignPermissionsReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RoleAssignPermissionsReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RoleAssignPermissionsReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RoleAssignPermissionsReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RoleAssignPermissionsReplyValidationError) ErrorName() string {
	return "RoleAssignPermissionsReplyValidationError"
}

// Error satisfies the builtin error interface
func (e RoleAssignPermissionsReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRoleAssignPermissionsReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RoleAssignPermissionsReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RoleAssignPermissionsReplyValidationError{}

// Validate checks the field values on RoleEntity with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RoleEntity) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RoleEntity with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RoleEntityMultiError, or
// nil if none found.
func (m *RoleEntity) ValidateAll() error {
	return m.validate(true)
}

func (m *RoleEntity) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Code

	// no validation rules for CreatedAt

	if len(errors) > 0 {
		return RoleEntityMultiError(errors)
	}

	return nil
}

// RoleEntityMultiError is an error wrapping multiple validation errors
// returned by RoleEntity.ValidateAll() if the designated constraints aren't met.
type RoleEntityMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RoleEntityMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RoleEntityMultiError) AllErrors() []error { return m }

// RoleEntityValidationError is the validation error returned by
// RoleEntity.Validate if the designated constraints aren't met.
type RoleEntityValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RoleEntityValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RoleEntityValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RoleEntityValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RoleEntityValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RoleEntityValidationError) ErrorName() string { return "RoleEntityValidationError" }

// Error satisfies the builtin error interface
func (e RoleEntityValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRoleEntity.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RoleEntityValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RoleEntityValidationError{}
