// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.2
// source: package/v1/package.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationPackageAssignPermissions = "/api.package.v1.Package/AssignPermissions"
const OperationPackageCreate = "/api.package.v1.Package/Create"
const OperationPackageDelete = "/api.package.v1.Package/Delete"
const OperationPackageGet = "/api.package.v1.Package/Get"
const OperationPackageList = "/api.package.v1.Package/List"
const OperationPackageUpdate = "/api.package.v1.Package/Update"

type PackageHTTPServer interface {
	// AssignPermissions 分配套餐权限
	AssignPermissions(context.Context, *PackageAssignPermissionsRequest) (*PackageAssignPermissionsReply, error)
	// Create 创建套餐
	Create(context.Context, *PackageCreateRequest) (*PackageCreateReply, error)
	// Delete 删除套餐
	Delete(context.Context, *PackageDeleteRequest) (*PackageDeleteReply, error)
	// Get 获取套餐详情
	Get(context.Context, *PackageGetRequest) (*PackageGetReply, error)
	// List 获取套餐列表
	List(context.Context, *PackageListRequest) (*PackageListReply, error)
	// Update 更新套餐
	Update(context.Context, *PackageUpdateRequest) (*PackageUpdateReply, error)
}

func RegisterPackageHTTPServer(s *http.Server, srv PackageHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/package/list", _Package_List4_HTTP_Handler(srv))
	r.GET("/api/v1/package/{id}", _Package_Get5_HTTP_Handler(srv))
	r.POST("/api/v1/package", _Package_Create5_HTTP_Handler(srv))
	r.PUT("/api/v1/package/{id}", _Package_Update5_HTTP_Handler(srv))
	r.DELETE("/api/v1/package/{id}", _Package_Delete5_HTTP_Handler(srv))
	r.PUT("/api/v1/package/{id}/permissions", _Package_AssignPermissions1_HTTP_Handler(srv))
}

func _Package_List4_HTTP_Handler(srv PackageHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PackageListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPackageList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.List(ctx, req.(*PackageListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PackageListReply)
		return ctx.Result(200, reply)
	}
}

func _Package_Get5_HTTP_Handler(srv PackageHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PackageGetRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPackageGet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Get(ctx, req.(*PackageGetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PackageGetReply)
		return ctx.Result(200, reply)
	}
}

func _Package_Create5_HTTP_Handler(srv PackageHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PackageCreateRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPackageCreate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Create(ctx, req.(*PackageCreateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PackageCreateReply)
		return ctx.Result(200, reply)
	}
}

func _Package_Update5_HTTP_Handler(srv PackageHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PackageUpdateRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPackageUpdate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Update(ctx, req.(*PackageUpdateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PackageUpdateReply)
		return ctx.Result(200, reply)
	}
}

func _Package_Delete5_HTTP_Handler(srv PackageHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PackageDeleteRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPackageDelete)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Delete(ctx, req.(*PackageDeleteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PackageDeleteReply)
		return ctx.Result(200, reply)
	}
}

func _Package_AssignPermissions1_HTTP_Handler(srv PackageHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PackageAssignPermissionsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPackageAssignPermissions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AssignPermissions(ctx, req.(*PackageAssignPermissionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PackageAssignPermissionsReply)
		return ctx.Result(200, reply)
	}
}

type PackageHTTPClient interface {
	// AssignPermissions 分配套餐权限
	AssignPermissions(ctx context.Context, req *PackageAssignPermissionsRequest, opts ...http.CallOption) (rsp *PackageAssignPermissionsReply, err error)
	// Create 创建套餐
	Create(ctx context.Context, req *PackageCreateRequest, opts ...http.CallOption) (rsp *PackageCreateReply, err error)
	// Delete 删除套餐
	Delete(ctx context.Context, req *PackageDeleteRequest, opts ...http.CallOption) (rsp *PackageDeleteReply, err error)
	// Get 获取套餐详情
	Get(ctx context.Context, req *PackageGetRequest, opts ...http.CallOption) (rsp *PackageGetReply, err error)
	// List 获取套餐列表
	List(ctx context.Context, req *PackageListRequest, opts ...http.CallOption) (rsp *PackageListReply, err error)
	// Update 更新套餐
	Update(ctx context.Context, req *PackageUpdateRequest, opts ...http.CallOption) (rsp *PackageUpdateReply, err error)
}

type PackageHTTPClientImpl struct {
	cc *http.Client
}

func NewPackageHTTPClient(client *http.Client) PackageHTTPClient {
	return &PackageHTTPClientImpl{client}
}

// AssignPermissions 分配套餐权限
func (c *PackageHTTPClientImpl) AssignPermissions(ctx context.Context, in *PackageAssignPermissionsRequest, opts ...http.CallOption) (*PackageAssignPermissionsReply, error) {
	var out PackageAssignPermissionsReply
	pattern := "/api/v1/package/{id}/permissions"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPackageAssignPermissions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Create 创建套餐
func (c *PackageHTTPClientImpl) Create(ctx context.Context, in *PackageCreateRequest, opts ...http.CallOption) (*PackageCreateReply, error) {
	var out PackageCreateReply
	pattern := "/api/v1/package"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPackageCreate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete 删除套餐
func (c *PackageHTTPClientImpl) Delete(ctx context.Context, in *PackageDeleteRequest, opts ...http.CallOption) (*PackageDeleteReply, error) {
	var out PackageDeleteReply
	pattern := "/api/v1/package/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPackageDelete))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Get 获取套餐详情
func (c *PackageHTTPClientImpl) Get(ctx context.Context, in *PackageGetRequest, opts ...http.CallOption) (*PackageGetReply, error) {
	var out PackageGetReply
	pattern := "/api/v1/package/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPackageGet))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// List 获取套餐列表
func (c *PackageHTTPClientImpl) List(ctx context.Context, in *PackageListRequest, opts ...http.CallOption) (*PackageListReply, error) {
	var out PackageListReply
	pattern := "/api/v1/package/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPackageList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Update 更新套餐
func (c *PackageHTTPClientImpl) Update(ctx context.Context, in *PackageUpdateRequest, opts ...http.CallOption) (*PackageUpdateReply, error) {
	var out PackageUpdateReply
	pattern := "/api/v1/package/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPackageUpdate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
