// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/package/v1/package.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on PackageListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PackageListRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PackageListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PackageListRequestMultiError, or nil if none found.
func (m *PackageListRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PackageListRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Status

	// no validation rules for Page

	// no validation rules for PageSize

	if len(errors) > 0 {
		return PackageListRequestMultiError(errors)
	}

	return nil
}

// PackageListRequestMultiError is an error wrapping multiple validation errors
// returned by PackageListRequest.ValidateAll() if the designated constraints
// aren't met.
type PackageListRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PackageListRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PackageListRequestMultiError) AllErrors() []error { return m }

// PackageListRequestValidationError is the validation error returned by
// PackageListRequest.Validate if the designated constraints aren't met.
type PackageListRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PackageListRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PackageListRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PackageListRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PackageListRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PackageListRequestValidationError) ErrorName() string {
	return "PackageListRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PackageListRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPackageListRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PackageListRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PackageListRequestValidationError{}

// Validate checks the field values on PackageListReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PackageListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PackageListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PackageListReplyMultiError, or nil if none found.
func (m *PackageListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *PackageListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PackageListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PackageListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PackageListReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return PackageListReplyMultiError(errors)
	}

	return nil
}

// PackageListReplyMultiError is an error wrapping multiple validation errors
// returned by PackageListReply.ValidateAll() if the designated constraints
// aren't met.
type PackageListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PackageListReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PackageListReplyMultiError) AllErrors() []error { return m }

// PackageListReplyValidationError is the validation error returned by
// PackageListReply.Validate if the designated constraints aren't met.
type PackageListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PackageListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PackageListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PackageListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PackageListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PackageListReplyValidationError) ErrorName() string { return "PackageListReplyValidationError" }

// Error satisfies the builtin error interface
func (e PackageListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPackageListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PackageListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PackageListReplyValidationError{}

// Validate checks the field values on PackageGetRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PackageGetRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PackageGetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PackageGetRequestMultiError, or nil if none found.
func (m *PackageGetRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PackageGetRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return PackageGetRequestMultiError(errors)
	}

	return nil
}

// PackageGetRequestMultiError is an error wrapping multiple validation errors
// returned by PackageGetRequest.ValidateAll() if the designated constraints
// aren't met.
type PackageGetRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PackageGetRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PackageGetRequestMultiError) AllErrors() []error { return m }

// PackageGetRequestValidationError is the validation error returned by
// PackageGetRequest.Validate if the designated constraints aren't met.
type PackageGetRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PackageGetRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PackageGetRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PackageGetRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PackageGetRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PackageGetRequestValidationError) ErrorName() string {
	return "PackageGetRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PackageGetRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPackageGetRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PackageGetRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PackageGetRequestValidationError{}

// Validate checks the field values on PackageGetReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PackageGetReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PackageGetReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PackageGetReplyMultiError, or nil if none found.
func (m *PackageGetReply) ValidateAll() error {
	return m.validate(true)
}

func (m *PackageGetReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetPkg()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PackageGetReplyValidationError{
					field:  "Pkg",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PackageGetReplyValidationError{
					field:  "Pkg",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPkg()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PackageGetReplyValidationError{
				field:  "Pkg",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return PackageGetReplyMultiError(errors)
	}

	return nil
}

// PackageGetReplyMultiError is an error wrapping multiple validation errors
// returned by PackageGetReply.ValidateAll() if the designated constraints
// aren't met.
type PackageGetReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PackageGetReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PackageGetReplyMultiError) AllErrors() []error { return m }

// PackageGetReplyValidationError is the validation error returned by
// PackageGetReply.Validate if the designated constraints aren't met.
type PackageGetReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PackageGetReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PackageGetReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PackageGetReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PackageGetReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PackageGetReplyValidationError) ErrorName() string { return "PackageGetReplyValidationError" }

// Error satisfies the builtin error interface
func (e PackageGetReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPackageGetReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PackageGetReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PackageGetReplyValidationError{}

// Validate checks the field values on PackageCreateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PackageCreateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PackageCreateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PackageCreateRequestMultiError, or nil if none found.
func (m *PackageCreateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PackageCreateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Code

	// no validation rules for Description

	if len(errors) > 0 {
		return PackageCreateRequestMultiError(errors)
	}

	return nil
}

// PackageCreateRequestMultiError is an error wrapping multiple validation
// errors returned by PackageCreateRequest.ValidateAll() if the designated
// constraints aren't met.
type PackageCreateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PackageCreateRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PackageCreateRequestMultiError) AllErrors() []error { return m }

// PackageCreateRequestValidationError is the validation error returned by
// PackageCreateRequest.Validate if the designated constraints aren't met.
type PackageCreateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PackageCreateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PackageCreateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PackageCreateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PackageCreateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PackageCreateRequestValidationError) ErrorName() string {
	return "PackageCreateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PackageCreateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPackageCreateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PackageCreateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PackageCreateRequestValidationError{}

// Validate checks the field values on PackageCreateReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PackageCreateReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PackageCreateReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PackageCreateReplyMultiError, or nil if none found.
func (m *PackageCreateReply) ValidateAll() error {
	return m.validate(true)
}

func (m *PackageCreateReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return PackageCreateReplyMultiError(errors)
	}

	return nil
}

// PackageCreateReplyMultiError is an error wrapping multiple validation errors
// returned by PackageCreateReply.ValidateAll() if the designated constraints
// aren't met.
type PackageCreateReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PackageCreateReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PackageCreateReplyMultiError) AllErrors() []error { return m }

// PackageCreateReplyValidationError is the validation error returned by
// PackageCreateReply.Validate if the designated constraints aren't met.
type PackageCreateReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PackageCreateReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PackageCreateReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PackageCreateReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PackageCreateReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PackageCreateReplyValidationError) ErrorName() string {
	return "PackageCreateReplyValidationError"
}

// Error satisfies the builtin error interface
func (e PackageCreateReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPackageCreateReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PackageCreateReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PackageCreateReplyValidationError{}

// Validate checks the field values on PackageUpdateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PackageUpdateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PackageUpdateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PackageUpdateRequestMultiError, or nil if none found.
func (m *PackageUpdateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PackageUpdateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Code

	// no validation rules for Description

	if len(errors) > 0 {
		return PackageUpdateRequestMultiError(errors)
	}

	return nil
}

// PackageUpdateRequestMultiError is an error wrapping multiple validation
// errors returned by PackageUpdateRequest.ValidateAll() if the designated
// constraints aren't met.
type PackageUpdateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PackageUpdateRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PackageUpdateRequestMultiError) AllErrors() []error { return m }

// PackageUpdateRequestValidationError is the validation error returned by
// PackageUpdateRequest.Validate if the designated constraints aren't met.
type PackageUpdateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PackageUpdateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PackageUpdateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PackageUpdateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PackageUpdateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PackageUpdateRequestValidationError) ErrorName() string {
	return "PackageUpdateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PackageUpdateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPackageUpdateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PackageUpdateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PackageUpdateRequestValidationError{}

// Validate checks the field values on PackageUpdateReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PackageUpdateReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PackageUpdateReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PackageUpdateReplyMultiError, or nil if none found.
func (m *PackageUpdateReply) ValidateAll() error {
	return m.validate(true)
}

func (m *PackageUpdateReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return PackageUpdateReplyMultiError(errors)
	}

	return nil
}

// PackageUpdateReplyMultiError is an error wrapping multiple validation errors
// returned by PackageUpdateReply.ValidateAll() if the designated constraints
// aren't met.
type PackageUpdateReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PackageUpdateReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PackageUpdateReplyMultiError) AllErrors() []error { return m }

// PackageUpdateReplyValidationError is the validation error returned by
// PackageUpdateReply.Validate if the designated constraints aren't met.
type PackageUpdateReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PackageUpdateReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PackageUpdateReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PackageUpdateReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PackageUpdateReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PackageUpdateReplyValidationError) ErrorName() string {
	return "PackageUpdateReplyValidationError"
}

// Error satisfies the builtin error interface
func (e PackageUpdateReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPackageUpdateReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PackageUpdateReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PackageUpdateReplyValidationError{}

// Validate checks the field values on PackageDeleteRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PackageDeleteRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PackageDeleteRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PackageDeleteRequestMultiError, or nil if none found.
func (m *PackageDeleteRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PackageDeleteRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return PackageDeleteRequestMultiError(errors)
	}

	return nil
}

// PackageDeleteRequestMultiError is an error wrapping multiple validation
// errors returned by PackageDeleteRequest.ValidateAll() if the designated
// constraints aren't met.
type PackageDeleteRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PackageDeleteRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PackageDeleteRequestMultiError) AllErrors() []error { return m }

// PackageDeleteRequestValidationError is the validation error returned by
// PackageDeleteRequest.Validate if the designated constraints aren't met.
type PackageDeleteRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PackageDeleteRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PackageDeleteRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PackageDeleteRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PackageDeleteRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PackageDeleteRequestValidationError) ErrorName() string {
	return "PackageDeleteRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PackageDeleteRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPackageDeleteRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PackageDeleteRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PackageDeleteRequestValidationError{}

// Validate checks the field values on PackageDeleteReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PackageDeleteReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PackageDeleteReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PackageDeleteReplyMultiError, or nil if none found.
func (m *PackageDeleteReply) ValidateAll() error {
	return m.validate(true)
}

func (m *PackageDeleteReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return PackageDeleteReplyMultiError(errors)
	}

	return nil
}

// PackageDeleteReplyMultiError is an error wrapping multiple validation errors
// returned by PackageDeleteReply.ValidateAll() if the designated constraints
// aren't met.
type PackageDeleteReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PackageDeleteReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PackageDeleteReplyMultiError) AllErrors() []error { return m }

// PackageDeleteReplyValidationError is the validation error returned by
// PackageDeleteReply.Validate if the designated constraints aren't met.
type PackageDeleteReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PackageDeleteReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PackageDeleteReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PackageDeleteReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PackageDeleteReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PackageDeleteReplyValidationError) ErrorName() string {
	return "PackageDeleteReplyValidationError"
}

// Error satisfies the builtin error interface
func (e PackageDeleteReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPackageDeleteReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PackageDeleteReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PackageDeleteReplyValidationError{}

// Validate checks the field values on PackageAssignPermissionsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PackageAssignPermissionsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PackageAssignPermissionsRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// PackageAssignPermissionsRequestMultiError, or nil if none found.
func (m *PackageAssignPermissionsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PackageAssignPermissionsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return PackageAssignPermissionsRequestMultiError(errors)
	}

	return nil
}

// PackageAssignPermissionsRequestMultiError is an error wrapping multiple
// validation errors returned by PackageAssignPermissionsRequest.ValidateAll()
// if the designated constraints aren't met.
type PackageAssignPermissionsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PackageAssignPermissionsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PackageAssignPermissionsRequestMultiError) AllErrors() []error { return m }

// PackageAssignPermissionsRequestValidationError is the validation error
// returned by PackageAssignPermissionsRequest.Validate if the designated
// constraints aren't met.
type PackageAssignPermissionsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PackageAssignPermissionsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PackageAssignPermissionsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PackageAssignPermissionsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PackageAssignPermissionsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PackageAssignPermissionsRequestValidationError) ErrorName() string {
	return "PackageAssignPermissionsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PackageAssignPermissionsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPackageAssignPermissionsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PackageAssignPermissionsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PackageAssignPermissionsRequestValidationError{}

// Validate checks the field values on PackageAssignPermissionsReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PackageAssignPermissionsReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PackageAssignPermissionsReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// PackageAssignPermissionsReplyMultiError, or nil if none found.
func (m *PackageAssignPermissionsReply) ValidateAll() error {
	return m.validate(true)
}

func (m *PackageAssignPermissionsReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return PackageAssignPermissionsReplyMultiError(errors)
	}

	return nil
}

// PackageAssignPermissionsReplyMultiError is an error wrapping multiple
// validation errors returned by PackageAssignPermissionsReply.ValidateAll()
// if the designated constraints aren't met.
type PackageAssignPermissionsReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PackageAssignPermissionsReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PackageAssignPermissionsReplyMultiError) AllErrors() []error { return m }

// PackageAssignPermissionsReplyValidationError is the validation error
// returned by PackageAssignPermissionsReply.Validate if the designated
// constraints aren't met.
type PackageAssignPermissionsReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PackageAssignPermissionsReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PackageAssignPermissionsReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PackageAssignPermissionsReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PackageAssignPermissionsReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PackageAssignPermissionsReplyValidationError) ErrorName() string {
	return "PackageAssignPermissionsReplyValidationError"
}

// Error satisfies the builtin error interface
func (e PackageAssignPermissionsReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPackageAssignPermissionsReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PackageAssignPermissionsReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PackageAssignPermissionsReplyValidationError{}

// Validate checks the field values on PackageEntity with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PackageEntity) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PackageEntity with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PackageEntityMultiError, or
// nil if none found.
func (m *PackageEntity) ValidateAll() error {
	return m.validate(true)
}

func (m *PackageEntity) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Code

	// no validation rules for Description

	// no validation rules for Status

	// no validation rules for CreatedAt

	if len(errors) > 0 {
		return PackageEntityMultiError(errors)
	}

	return nil
}

// PackageEntityMultiError is an error wrapping multiple validation errors
// returned by PackageEntity.ValidateAll() if the designated constraints
// aren't met.
type PackageEntityMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PackageEntityMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PackageEntityMultiError) AllErrors() []error { return m }

// PackageEntityValidationError is the validation error returned by
// PackageEntity.Validate if the designated constraints aren't met.
type PackageEntityValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PackageEntityValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PackageEntityValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PackageEntityValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PackageEntityValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PackageEntityValidationError) ErrorName() string { return "PackageEntityValidationError" }

// Error satisfies the builtin error interface
func (e PackageEntityValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPackageEntity.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PackageEntityValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PackageEntityValidationError{}
