// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/permission/v1/permission.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on PermissionTreeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PermissionTreeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PermissionTreeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PermissionTreeRequestMultiError, or nil if none found.
func (m *PermissionTreeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PermissionTreeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return PermissionTreeRequestMultiError(errors)
	}

	return nil
}

// PermissionTreeRequestMultiError is an error wrapping multiple validation
// errors returned by PermissionTreeRequest.ValidateAll() if the designated
// constraints aren't met.
type PermissionTreeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PermissionTreeRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PermissionTreeRequestMultiError) AllErrors() []error { return m }

// PermissionTreeRequestValidationError is the validation error returned by
// PermissionTreeRequest.Validate if the designated constraints aren't met.
type PermissionTreeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PermissionTreeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PermissionTreeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PermissionTreeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PermissionTreeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PermissionTreeRequestValidationError) ErrorName() string {
	return "PermissionTreeRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PermissionTreeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPermissionTreeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PermissionTreeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PermissionTreeRequestValidationError{}

// Validate checks the field values on PermissionTreeReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PermissionTreeReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PermissionTreeReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PermissionTreeReplyMultiError, or nil if none found.
func (m *PermissionTreeReply) ValidateAll() error {
	return m.validate(true)
}

func (m *PermissionTreeReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PermissionTreeReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PermissionTreeReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PermissionTreeReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return PermissionTreeReplyMultiError(errors)
	}

	return nil
}

// PermissionTreeReplyMultiError is an error wrapping multiple validation
// errors returned by PermissionTreeReply.ValidateAll() if the designated
// constraints aren't met.
type PermissionTreeReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PermissionTreeReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PermissionTreeReplyMultiError) AllErrors() []error { return m }

// PermissionTreeReplyValidationError is the validation error returned by
// PermissionTreeReply.Validate if the designated constraints aren't met.
type PermissionTreeReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PermissionTreeReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PermissionTreeReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PermissionTreeReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PermissionTreeReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PermissionTreeReplyValidationError) ErrorName() string {
	return "PermissionTreeReplyValidationError"
}

// Error satisfies the builtin error interface
func (e PermissionTreeReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPermissionTreeReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PermissionTreeReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PermissionTreeReplyValidationError{}

// Validate checks the field values on PermissionGetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PermissionGetRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PermissionGetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PermissionGetRequestMultiError, or nil if none found.
func (m *PermissionGetRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PermissionGetRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return PermissionGetRequestMultiError(errors)
	}

	return nil
}

// PermissionGetRequestMultiError is an error wrapping multiple validation
// errors returned by PermissionGetRequest.ValidateAll() if the designated
// constraints aren't met.
type PermissionGetRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PermissionGetRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PermissionGetRequestMultiError) AllErrors() []error { return m }

// PermissionGetRequestValidationError is the validation error returned by
// PermissionGetRequest.Validate if the designated constraints aren't met.
type PermissionGetRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PermissionGetRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PermissionGetRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PermissionGetRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PermissionGetRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PermissionGetRequestValidationError) ErrorName() string {
	return "PermissionGetRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PermissionGetRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPermissionGetRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PermissionGetRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PermissionGetRequestValidationError{}

// Validate checks the field values on PermissionGetReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PermissionGetReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PermissionGetReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PermissionGetReplyMultiError, or nil if none found.
func (m *PermissionGetReply) ValidateAll() error {
	return m.validate(true)
}

func (m *PermissionGetReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetPermission()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PermissionGetReplyValidationError{
					field:  "Permission",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PermissionGetReplyValidationError{
					field:  "Permission",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPermission()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PermissionGetReplyValidationError{
				field:  "Permission",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return PermissionGetReplyMultiError(errors)
	}

	return nil
}

// PermissionGetReplyMultiError is an error wrapping multiple validation errors
// returned by PermissionGetReply.ValidateAll() if the designated constraints
// aren't met.
type PermissionGetReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PermissionGetReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PermissionGetReplyMultiError) AllErrors() []error { return m }

// PermissionGetReplyValidationError is the validation error returned by
// PermissionGetReply.Validate if the designated constraints aren't met.
type PermissionGetReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PermissionGetReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PermissionGetReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PermissionGetReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PermissionGetReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PermissionGetReplyValidationError) ErrorName() string {
	return "PermissionGetReplyValidationError"
}

// Error satisfies the builtin error interface
func (e PermissionGetReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPermissionGetReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PermissionGetReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PermissionGetReplyValidationError{}

// Validate checks the field values on PermissionCreateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PermissionCreateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PermissionCreateRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PermissionCreateRequestMultiError, or nil if none found.
func (m *PermissionCreateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PermissionCreateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ParentId

	// no validation rules for Name

	// no validation rules for Code

	// no validation rules for Type

	// no validation rules for ApiPath

	// no validation rules for ApiMethod

	// no validation rules for Sort

	// no validation rules for Path

	// no validation rules for Component

	// no validation rules for Redirect

	// no validation rules for Icon

	// no validation rules for OrderNo

	// no validation rules for Hidden

	// no validation rules for KeepAlive

	// no validation rules for FrameSrc

	// no validation rules for FrameBlank

	if len(errors) > 0 {
		return PermissionCreateRequestMultiError(errors)
	}

	return nil
}

// PermissionCreateRequestMultiError is an error wrapping multiple validation
// errors returned by PermissionCreateRequest.ValidateAll() if the designated
// constraints aren't met.
type PermissionCreateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PermissionCreateRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PermissionCreateRequestMultiError) AllErrors() []error { return m }

// PermissionCreateRequestValidationError is the validation error returned by
// PermissionCreateRequest.Validate if the designated constraints aren't met.
type PermissionCreateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PermissionCreateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PermissionCreateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PermissionCreateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PermissionCreateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PermissionCreateRequestValidationError) ErrorName() string {
	return "PermissionCreateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PermissionCreateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPermissionCreateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PermissionCreateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PermissionCreateRequestValidationError{}

// Validate checks the field values on PermissionCreateReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PermissionCreateReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PermissionCreateReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PermissionCreateReplyMultiError, or nil if none found.
func (m *PermissionCreateReply) ValidateAll() error {
	return m.validate(true)
}

func (m *PermissionCreateReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return PermissionCreateReplyMultiError(errors)
	}

	return nil
}

// PermissionCreateReplyMultiError is an error wrapping multiple validation
// errors returned by PermissionCreateReply.ValidateAll() if the designated
// constraints aren't met.
type PermissionCreateReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PermissionCreateReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PermissionCreateReplyMultiError) AllErrors() []error { return m }

// PermissionCreateReplyValidationError is the validation error returned by
// PermissionCreateReply.Validate if the designated constraints aren't met.
type PermissionCreateReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PermissionCreateReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PermissionCreateReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PermissionCreateReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PermissionCreateReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PermissionCreateReplyValidationError) ErrorName() string {
	return "PermissionCreateReplyValidationError"
}

// Error satisfies the builtin error interface
func (e PermissionCreateReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPermissionCreateReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PermissionCreateReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PermissionCreateReplyValidationError{}

// Validate checks the field values on PermissionUpdateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PermissionUpdateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PermissionUpdateRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PermissionUpdateRequestMultiError, or nil if none found.
func (m *PermissionUpdateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PermissionUpdateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for ParentId

	// no validation rules for Name

	// no validation rules for Code

	// no validation rules for Type

	// no validation rules for ApiPath

	// no validation rules for ApiMethod

	// no validation rules for Sort

	// no validation rules for Path

	// no validation rules for Component

	// no validation rules for Redirect

	// no validation rules for Icon

	// no validation rules for OrderNo

	// no validation rules for Hidden

	// no validation rules for KeepAlive

	// no validation rules for FrameSrc

	// no validation rules for FrameBlank

	if len(errors) > 0 {
		return PermissionUpdateRequestMultiError(errors)
	}

	return nil
}

// PermissionUpdateRequestMultiError is an error wrapping multiple validation
// errors returned by PermissionUpdateRequest.ValidateAll() if the designated
// constraints aren't met.
type PermissionUpdateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PermissionUpdateRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PermissionUpdateRequestMultiError) AllErrors() []error { return m }

// PermissionUpdateRequestValidationError is the validation error returned by
// PermissionUpdateRequest.Validate if the designated constraints aren't met.
type PermissionUpdateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PermissionUpdateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PermissionUpdateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PermissionUpdateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PermissionUpdateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PermissionUpdateRequestValidationError) ErrorName() string {
	return "PermissionUpdateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PermissionUpdateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPermissionUpdateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PermissionUpdateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PermissionUpdateRequestValidationError{}

// Validate checks the field values on PermissionUpdateReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PermissionUpdateReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PermissionUpdateReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PermissionUpdateReplyMultiError, or nil if none found.
func (m *PermissionUpdateReply) ValidateAll() error {
	return m.validate(true)
}

func (m *PermissionUpdateReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return PermissionUpdateReplyMultiError(errors)
	}

	return nil
}

// PermissionUpdateReplyMultiError is an error wrapping multiple validation
// errors returned by PermissionUpdateReply.ValidateAll() if the designated
// constraints aren't met.
type PermissionUpdateReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PermissionUpdateReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PermissionUpdateReplyMultiError) AllErrors() []error { return m }

// PermissionUpdateReplyValidationError is the validation error returned by
// PermissionUpdateReply.Validate if the designated constraints aren't met.
type PermissionUpdateReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PermissionUpdateReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PermissionUpdateReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PermissionUpdateReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PermissionUpdateReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PermissionUpdateReplyValidationError) ErrorName() string {
	return "PermissionUpdateReplyValidationError"
}

// Error satisfies the builtin error interface
func (e PermissionUpdateReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPermissionUpdateReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PermissionUpdateReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PermissionUpdateReplyValidationError{}

// Validate checks the field values on PermissionDeleteRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PermissionDeleteRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PermissionDeleteRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PermissionDeleteRequestMultiError, or nil if none found.
func (m *PermissionDeleteRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PermissionDeleteRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return PermissionDeleteRequestMultiError(errors)
	}

	return nil
}

// PermissionDeleteRequestMultiError is an error wrapping multiple validation
// errors returned by PermissionDeleteRequest.ValidateAll() if the designated
// constraints aren't met.
type PermissionDeleteRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PermissionDeleteRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PermissionDeleteRequestMultiError) AllErrors() []error { return m }

// PermissionDeleteRequestValidationError is the validation error returned by
// PermissionDeleteRequest.Validate if the designated constraints aren't met.
type PermissionDeleteRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PermissionDeleteRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PermissionDeleteRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PermissionDeleteRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PermissionDeleteRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PermissionDeleteRequestValidationError) ErrorName() string {
	return "PermissionDeleteRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PermissionDeleteRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPermissionDeleteRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PermissionDeleteRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PermissionDeleteRequestValidationError{}

// Validate checks the field values on PermissionDeleteReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PermissionDeleteReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PermissionDeleteReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PermissionDeleteReplyMultiError, or nil if none found.
func (m *PermissionDeleteReply) ValidateAll() error {
	return m.validate(true)
}

func (m *PermissionDeleteReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return PermissionDeleteReplyMultiError(errors)
	}

	return nil
}

// PermissionDeleteReplyMultiError is an error wrapping multiple validation
// errors returned by PermissionDeleteReply.ValidateAll() if the designated
// constraints aren't met.
type PermissionDeleteReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PermissionDeleteReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PermissionDeleteReplyMultiError) AllErrors() []error { return m }

// PermissionDeleteReplyValidationError is the validation error returned by
// PermissionDeleteReply.Validate if the designated constraints aren't met.
type PermissionDeleteReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PermissionDeleteReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PermissionDeleteReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PermissionDeleteReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PermissionDeleteReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PermissionDeleteReplyValidationError) ErrorName() string {
	return "PermissionDeleteReplyValidationError"
}

// Error satisfies the builtin error interface
func (e PermissionDeleteReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPermissionDeleteReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PermissionDeleteReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PermissionDeleteReplyValidationError{}

// Validate checks the field values on GetUserMenuRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserMenuRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserMenuRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserMenuRequestMultiError, or nil if none found.
func (m *GetUserMenuRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserMenuRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetUserMenuRequestMultiError(errors)
	}

	return nil
}

// GetUserMenuRequestMultiError is an error wrapping multiple validation errors
// returned by GetUserMenuRequest.ValidateAll() if the designated constraints
// aren't met.
type GetUserMenuRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserMenuRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserMenuRequestMultiError) AllErrors() []error { return m }

// GetUserMenuRequestValidationError is the validation error returned by
// GetUserMenuRequest.Validate if the designated constraints aren't met.
type GetUserMenuRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserMenuRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserMenuRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserMenuRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserMenuRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserMenuRequestValidationError) ErrorName() string {
	return "GetUserMenuRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserMenuRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserMenuRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserMenuRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserMenuRequestValidationError{}

// Validate checks the field values on GetUserMenuReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetUserMenuReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserMenuReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserMenuReplyMultiError, or nil if none found.
func (m *GetUserMenuReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserMenuReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetUserMenuReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetUserMenuReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetUserMenuReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetUserMenuReplyMultiError(errors)
	}

	return nil
}

// GetUserMenuReplyMultiError is an error wrapping multiple validation errors
// returned by GetUserMenuReply.ValidateAll() if the designated constraints
// aren't met.
type GetUserMenuReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserMenuReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserMenuReplyMultiError) AllErrors() []error { return m }

// GetUserMenuReplyValidationError is the validation error returned by
// GetUserMenuReply.Validate if the designated constraints aren't met.
type GetUserMenuReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserMenuReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserMenuReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserMenuReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserMenuReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserMenuReplyValidationError) ErrorName() string { return "GetUserMenuReplyValidationError" }

// Error satisfies the builtin error interface
func (e GetUserMenuReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserMenuReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserMenuReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserMenuReplyValidationError{}

// Validate checks the field values on MenuItem with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MenuItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MenuItem with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MenuItemMultiError, or nil
// if none found.
func (m *MenuItem) ValidateAll() error {
	return m.validate(true)
}

func (m *MenuItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Path

	// no validation rules for Name

	// no validation rules for Component

	// no validation rules for Redirect

	if all {
		switch v := interface{}(m.GetMeta()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MenuItemValidationError{
					field:  "Meta",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MenuItemValidationError{
					field:  "Meta",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMeta()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MenuItemValidationError{
				field:  "Meta",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetChildren() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, MenuItemValidationError{
						field:  fmt.Sprintf("Children[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, MenuItemValidationError{
						field:  fmt.Sprintf("Children[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return MenuItemValidationError{
					field:  fmt.Sprintf("Children[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return MenuItemMultiError(errors)
	}

	return nil
}

// MenuItemMultiError is an error wrapping multiple validation errors returned
// by MenuItem.ValidateAll() if the designated constraints aren't met.
type MenuItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MenuItemMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MenuItemMultiError) AllErrors() []error { return m }

// MenuItemValidationError is the validation error returned by
// MenuItem.Validate if the designated constraints aren't met.
type MenuItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MenuItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MenuItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MenuItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MenuItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MenuItemValidationError) ErrorName() string { return "MenuItemValidationError" }

// Error satisfies the builtin error interface
func (e MenuItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMenuItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MenuItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MenuItemValidationError{}

// Validate checks the field values on MenuMeta with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MenuMeta) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MenuMeta with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MenuMetaMultiError, or nil
// if none found.
func (m *MenuMeta) ValidateAll() error {
	return m.validate(true)
}

func (m *MenuMeta) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Title

	// no validation rules for Icon

	// no validation rules for OrderNo

	// no validation rules for Hidden

	// no validation rules for KeepAlive

	// no validation rules for FrameSrc

	// no validation rules for FrameBlank

	if len(errors) > 0 {
		return MenuMetaMultiError(errors)
	}

	return nil
}

// MenuMetaMultiError is an error wrapping multiple validation errors returned
// by MenuMeta.ValidateAll() if the designated constraints aren't met.
type MenuMetaMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MenuMetaMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MenuMetaMultiError) AllErrors() []error { return m }

// MenuMetaValidationError is the validation error returned by
// MenuMeta.Validate if the designated constraints aren't met.
type MenuMetaValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MenuMetaValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MenuMetaValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MenuMetaValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MenuMetaValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MenuMetaValidationError) ErrorName() string { return "MenuMetaValidationError" }

// Error satisfies the builtin error interface
func (e MenuMetaValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMenuMeta.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MenuMetaValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MenuMetaValidationError{}

// Validate checks the field values on PermissionEntity with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PermissionEntity) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PermissionEntity with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PermissionEntityMultiError, or nil if none found.
func (m *PermissionEntity) ValidateAll() error {
	return m.validate(true)
}

func (m *PermissionEntity) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for ParentId

	// no validation rules for Name

	// no validation rules for Code

	// no validation rules for Type

	// no validation rules for ApiPath

	// no validation rules for ApiMethod

	// no validation rules for Sort

	// no validation rules for CreatedAt

	for idx, item := range m.GetChildren() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PermissionEntityValidationError{
						field:  fmt.Sprintf("Children[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PermissionEntityValidationError{
						field:  fmt.Sprintf("Children[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PermissionEntityValidationError{
					field:  fmt.Sprintf("Children[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Path

	// no validation rules for Component

	// no validation rules for Redirect

	// no validation rules for Icon

	// no validation rules for OrderNo

	// no validation rules for Hidden

	// no validation rules for KeepAlive

	// no validation rules for FrameSrc

	// no validation rules for FrameBlank

	if len(errors) > 0 {
		return PermissionEntityMultiError(errors)
	}

	return nil
}

// PermissionEntityMultiError is an error wrapping multiple validation errors
// returned by PermissionEntity.ValidateAll() if the designated constraints
// aren't met.
type PermissionEntityMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PermissionEntityMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PermissionEntityMultiError) AllErrors() []error { return m }

// PermissionEntityValidationError is the validation error returned by
// PermissionEntity.Validate if the designated constraints aren't met.
type PermissionEntityValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PermissionEntityValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PermissionEntityValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PermissionEntityValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PermissionEntityValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PermissionEntityValidationError) ErrorName() string { return "PermissionEntityValidationError" }

// Error satisfies the builtin error interface
func (e PermissionEntityValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPermissionEntity.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PermissionEntityValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PermissionEntityValidationError{}
