// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: permission/v1/permission.proto

package v1

import (
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ========== 权限树 ==========
type PermissionTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionTreeRequest) Reset() {
	*x = PermissionTreeRequest{}
	mi := &file_permission_v1_permission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionTreeRequest) ProtoMessage() {}

func (x *PermissionTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_permission_v1_permission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionTreeRequest.ProtoReflect.Descriptor instead.
func (*PermissionTreeRequest) Descriptor() ([]byte, []int) {
	return file_permission_v1_permission_proto_rawDescGZIP(), []int{0}
}

type PermissionTreeReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 权限列表
	List          []*PermissionEntity `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionTreeReply) Reset() {
	*x = PermissionTreeReply{}
	mi := &file_permission_v1_permission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionTreeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionTreeReply) ProtoMessage() {}

func (x *PermissionTreeReply) ProtoReflect() protoreflect.Message {
	mi := &file_permission_v1_permission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionTreeReply.ProtoReflect.Descriptor instead.
func (*PermissionTreeReply) Descriptor() ([]byte, []int) {
	return file_permission_v1_permission_proto_rawDescGZIP(), []int{1}
}

func (x *PermissionTreeReply) GetList() []*PermissionEntity {
	if x != nil {
		return x.List
	}
	return nil
}

// ========== 权限详情 ==========
type PermissionGetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 权限ID
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionGetRequest) Reset() {
	*x = PermissionGetRequest{}
	mi := &file_permission_v1_permission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionGetRequest) ProtoMessage() {}

func (x *PermissionGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_permission_v1_permission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionGetRequest.ProtoReflect.Descriptor instead.
func (*PermissionGetRequest) Descriptor() ([]byte, []int) {
	return file_permission_v1_permission_proto_rawDescGZIP(), []int{2}
}

func (x *PermissionGetRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PermissionGetReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 权限信息
	Permission    *PermissionEntity `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionGetReply) Reset() {
	*x = PermissionGetReply{}
	mi := &file_permission_v1_permission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionGetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionGetReply) ProtoMessage() {}

func (x *PermissionGetReply) ProtoReflect() protoreflect.Message {
	mi := &file_permission_v1_permission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionGetReply.ProtoReflect.Descriptor instead.
func (*PermissionGetReply) Descriptor() ([]byte, []int) {
	return file_permission_v1_permission_proto_rawDescGZIP(), []int{3}
}

func (x *PermissionGetReply) GetPermission() *PermissionEntity {
	if x != nil {
		return x.Permission
	}
	return nil
}

// ========== 创建权限 ==========
type PermissionCreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 父权限ID
	ParentId int64 `protobuf:"varint,1,opt,name=parent_id,proto3" json:"parent_id,omitempty"`
	// 权限名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 权限编码
	Code string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	// 类型：MENU/BUTTON/API
	Type string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	// API路径
	ApiPath string `protobuf:"bytes,5,opt,name=api_path,proto3" json:"api_path,omitempty"`
	// API方法
	ApiMethod string `protobuf:"bytes,6,opt,name=api_method,proto3" json:"api_method,omitempty"`
	// 排序
	Sort          int32 `protobuf:"varint,7,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionCreateRequest) Reset() {
	*x = PermissionCreateRequest{}
	mi := &file_permission_v1_permission_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionCreateRequest) ProtoMessage() {}

func (x *PermissionCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_permission_v1_permission_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionCreateRequest.ProtoReflect.Descriptor instead.
func (*PermissionCreateRequest) Descriptor() ([]byte, []int) {
	return file_permission_v1_permission_proto_rawDescGZIP(), []int{4}
}

func (x *PermissionCreateRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *PermissionCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PermissionCreateRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PermissionCreateRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PermissionCreateRequest) GetApiPath() string {
	if x != nil {
		return x.ApiPath
	}
	return ""
}

func (x *PermissionCreateRequest) GetApiMethod() string {
	if x != nil {
		return x.ApiMethod
	}
	return ""
}

func (x *PermissionCreateRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type PermissionCreateReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 权限ID
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionCreateReply) Reset() {
	*x = PermissionCreateReply{}
	mi := &file_permission_v1_permission_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionCreateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionCreateReply) ProtoMessage() {}

func (x *PermissionCreateReply) ProtoReflect() protoreflect.Message {
	mi := &file_permission_v1_permission_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionCreateReply.ProtoReflect.Descriptor instead.
func (*PermissionCreateReply) Descriptor() ([]byte, []int) {
	return file_permission_v1_permission_proto_rawDescGZIP(), []int{5}
}

func (x *PermissionCreateReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// ========== 更新权限 ==========
type PermissionUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 权限ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 父权限ID
	ParentId int64 `protobuf:"varint,2,opt,name=parent_id,proto3" json:"parent_id,omitempty"`
	// 权限名称
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// 权限编码
	Code string `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	// 类型：MENU/BUTTON/API
	Type string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	// API路径
	ApiPath string `protobuf:"bytes,6,opt,name=api_path,proto3" json:"api_path,omitempty"`
	// API方法
	ApiMethod string `protobuf:"bytes,7,opt,name=api_method,proto3" json:"api_method,omitempty"`
	// 排序
	Sort          int32 `protobuf:"varint,8,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionUpdateRequest) Reset() {
	*x = PermissionUpdateRequest{}
	mi := &file_permission_v1_permission_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionUpdateRequest) ProtoMessage() {}

func (x *PermissionUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_permission_v1_permission_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionUpdateRequest.ProtoReflect.Descriptor instead.
func (*PermissionUpdateRequest) Descriptor() ([]byte, []int) {
	return file_permission_v1_permission_proto_rawDescGZIP(), []int{6}
}

func (x *PermissionUpdateRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PermissionUpdateRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *PermissionUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PermissionUpdateRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PermissionUpdateRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PermissionUpdateRequest) GetApiPath() string {
	if x != nil {
		return x.ApiPath
	}
	return ""
}

func (x *PermissionUpdateRequest) GetApiMethod() string {
	if x != nil {
		return x.ApiMethod
	}
	return ""
}

func (x *PermissionUpdateRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type PermissionUpdateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionUpdateReply) Reset() {
	*x = PermissionUpdateReply{}
	mi := &file_permission_v1_permission_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionUpdateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionUpdateReply) ProtoMessage() {}

func (x *PermissionUpdateReply) ProtoReflect() protoreflect.Message {
	mi := &file_permission_v1_permission_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionUpdateReply.ProtoReflect.Descriptor instead.
func (*PermissionUpdateReply) Descriptor() ([]byte, []int) {
	return file_permission_v1_permission_proto_rawDescGZIP(), []int{7}
}

// ========== 删除权限 ==========
type PermissionDeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 权限ID
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionDeleteRequest) Reset() {
	*x = PermissionDeleteRequest{}
	mi := &file_permission_v1_permission_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionDeleteRequest) ProtoMessage() {}

func (x *PermissionDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_permission_v1_permission_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionDeleteRequest.ProtoReflect.Descriptor instead.
func (*PermissionDeleteRequest) Descriptor() ([]byte, []int) {
	return file_permission_v1_permission_proto_rawDescGZIP(), []int{8}
}

func (x *PermissionDeleteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PermissionDeleteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionDeleteReply) Reset() {
	*x = PermissionDeleteReply{}
	mi := &file_permission_v1_permission_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionDeleteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionDeleteReply) ProtoMessage() {}

func (x *PermissionDeleteReply) ProtoReflect() protoreflect.Message {
	mi := &file_permission_v1_permission_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionDeleteReply.ProtoReflect.Descriptor instead.
func (*PermissionDeleteReply) Descriptor() ([]byte, []int) {
	return file_permission_v1_permission_proto_rawDescGZIP(), []int{9}
}

// ========== 权限实体 ==========
type PermissionEntity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 权限ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 父权限ID
	ParentId int64 `protobuf:"varint,2,opt,name=parent_id,proto3" json:"parent_id,omitempty"`
	// 权限名称
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// 权限编码
	Code string `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	// 类型：MENU/BUTTON/API
	Type string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	// API路径
	ApiPath string `protobuf:"bytes,6,opt,name=api_path,proto3" json:"api_path,omitempty"`
	// API方法
	ApiMethod string `protobuf:"bytes,7,opt,name=api_method,proto3" json:"api_method,omitempty"`
	// 排序
	Sort int32 `protobuf:"varint,8,opt,name=sort,proto3" json:"sort,omitempty"`
	// 创建时间
	CreatedAt int64 `protobuf:"varint,9,opt,name=created_at,proto3" json:"created_at,omitempty"`
	// 子权限
	Children      []*PermissionEntity `protobuf:"bytes,10,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionEntity) Reset() {
	*x = PermissionEntity{}
	mi := &file_permission_v1_permission_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionEntity) ProtoMessage() {}

func (x *PermissionEntity) ProtoReflect() protoreflect.Message {
	mi := &file_permission_v1_permission_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionEntity.ProtoReflect.Descriptor instead.
func (*PermissionEntity) Descriptor() ([]byte, []int) {
	return file_permission_v1_permission_proto_rawDescGZIP(), []int{10}
}

func (x *PermissionEntity) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PermissionEntity) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *PermissionEntity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PermissionEntity) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PermissionEntity) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PermissionEntity) GetApiPath() string {
	if x != nil {
		return x.ApiPath
	}
	return ""
}

func (x *PermissionEntity) GetApiMethod() string {
	if x != nil {
		return x.ApiMethod
	}
	return ""
}

func (x *PermissionEntity) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *PermissionEntity) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PermissionEntity) GetChildren() []*PermissionEntity {
	if x != nil {
		return x.Children
	}
	return nil
}

var File_permission_v1_permission_proto protoreflect.FileDescriptor

const file_permission_v1_permission_proto_rawDesc = "" +
	"\n" +
	"\x1epermission/v1/permission.proto\x12\x11api.permission.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1copenapi/v3/annotations.proto\"\x17\n" +
	"\x15PermissionTreeRequest\"b\n" +
	"\x13PermissionTreeReply\x12K\n" +
	"\x04list\x18\x01 \x03(\v2#.api.permission.v1.PermissionEntityB\x12\xbaG\x0f\x92\x02\f权限列表R\x04list\":\n" +
	"\x14PermissionGetRequest\x12\"\n" +
	"\x02id\x18\x01 \x01(\x03B\x12\xe2A\x01\x02\xbaG\v\x92\x02\b权限IDR\x02id\"m\n" +
	"\x12PermissionGetReply\x12W\n" +
	"\n" +
	"permission\x18\x01 \x01(\v2#.api.permission.v1.PermissionEntityB\x12\xbaG\x0f\x92\x02\f权限信息R\n" +
	"permission\"\xda\x02\n" +
	"\x17PermissionCreateRequest\x12/\n" +
	"\tparent_id\x18\x01 \x01(\x03B\x11\xbaG\x0e\x92\x02\v父权限IDR\tparent_id\x12*\n" +
	"\x04name\x18\x02 \x01(\tB\x16\xe2A\x01\x02\xbaG\x0f\x92\x02\f权限名称R\x04name\x12*\n" +
	"\x04code\x18\x03 \x01(\tB\x16\xe2A\x01\x02\xbaG\x0f\x92\x02\f权限编码R\x04code\x126\n" +
	"\x04type\x18\x04 \x01(\tB\"\xe2A\x01\x02\xbaG\x1b\x92\x02\x18类型：MENU/BUTTON/APIR\x04type\x12+\n" +
	"\bapi_path\x18\x05 \x01(\tB\x0f\xbaG\f\x92\x02\tAPI路径R\bapi_path\x12/\n" +
	"\n" +
	"api_method\x18\x06 \x01(\tB\x0f\xbaG\f\x92\x02\tAPI方法R\n" +
	"api_method\x12 \n" +
	"\x04sort\x18\a \x01(\x05B\f\xbaG\t\x92\x02\x06排序R\x04sort\"7\n" +
	"\x15PermissionCreateReply\x12\x1e\n" +
	"\x02id\x18\x01 \x01(\x03B\x0e\xbaG\v\x92\x02\b权限IDR\x02id\"\xfe\x02\n" +
	"\x17PermissionUpdateRequest\x12\"\n" +
	"\x02id\x18\x01 \x01(\x03B\x12\xe2A\x01\x02\xbaG\v\x92\x02\b权限IDR\x02id\x12/\n" +
	"\tparent_id\x18\x02 \x01(\x03B\x11\xbaG\x0e\x92\x02\v父权限IDR\tparent_id\x12*\n" +
	"\x04name\x18\x03 \x01(\tB\x16\xe2A\x01\x02\xbaG\x0f\x92\x02\f权限名称R\x04name\x12*\n" +
	"\x04code\x18\x04 \x01(\tB\x16\xe2A\x01\x02\xbaG\x0f\x92\x02\f权限编码R\x04code\x126\n" +
	"\x04type\x18\x05 \x01(\tB\"\xe2A\x01\x02\xbaG\x1b\x92\x02\x18类型：MENU/BUTTON/APIR\x04type\x12+\n" +
	"\bapi_path\x18\x06 \x01(\tB\x0f\xbaG\f\x92\x02\tAPI路径R\bapi_path\x12/\n" +
	"\n" +
	"api_method\x18\a \x01(\tB\x0f\xbaG\f\x92\x02\tAPI方法R\n" +
	"api_method\x12 \n" +
	"\x04sort\x18\b \x01(\x05B\f\xbaG\t\x92\x02\x06排序R\x04sort\"\x17\n" +
	"\x15PermissionUpdateReply\"=\n" +
	"\x17PermissionDeleteRequest\x12\"\n" +
	"\x02id\x18\x01 \x01(\x03B\x12\xe2A\x01\x02\xbaG\v\x92\x02\b权限IDR\x02id\"\x17\n" +
	"\x15PermissionDeleteReply\"\xed\x03\n" +
	"\x10PermissionEntity\x12\x1e\n" +
	"\x02id\x18\x01 \x01(\x03B\x0e\xbaG\v\x92\x02\b权限IDR\x02id\x12/\n" +
	"\tparent_id\x18\x02 \x01(\x03B\x11\xbaG\x0e\x92\x02\v父权限IDR\tparent_id\x12&\n" +
	"\x04name\x18\x03 \x01(\tB\x12\xbaG\x0f\x92\x02\f权限名称R\x04name\x12&\n" +
	"\x04code\x18\x04 \x01(\tB\x12\xbaG\x0f\x92\x02\f权限编码R\x04code\x122\n" +
	"\x04type\x18\x05 \x01(\tB\x1e\xbaG\x1b\x92\x02\x18类型：MENU/BUTTON/APIR\x04type\x12+\n" +
	"\bapi_path\x18\x06 \x01(\tB\x0f\xbaG\f\x92\x02\tAPI路径R\bapi_path\x12/\n" +
	"\n" +
	"api_method\x18\a \x01(\tB\x0f\xbaG\f\x92\x02\tAPI方法R\n" +
	"api_method\x12 \n" +
	"\x04sort\x18\b \x01(\x05B\f\xbaG\t\x92\x02\x06排序R\x04sort\x122\n" +
	"\n" +
	"created_at\x18\t \x01(\x03B\x12\xbaG\x0f\x92\x02\f创建时间R\n" +
	"created_at\x12P\n" +
	"\bchildren\x18\n" +
	" \x03(\v2#.api.permission.v1.PermissionEntityB\x0f\xbaG\f\x92\x02\t子权限R\bchildren2\xe6\x05\n" +
	"\n" +
	"Permission\x12\x8d\x01\n" +
	"\x04Tree\x12(.api.permission.v1.PermissionTreeRequest\x1a&.api.permission.v1.PermissionTreeReply\"3\xbaG\x11\x12\x0f获取权限树\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/permission/tree\x12\x8d\x01\n" +
	"\x03Get\x12'.api.permission.v1.PermissionGetRequest\x1a%.api.permission.v1.PermissionGetReply\"6\xbaG\x14\x12\x12获取权限详情\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/permission/{id}\x12\x8e\x01\n" +
	"\x06Create\x12*.api.permission.v1.PermissionCreateRequest\x1a(.api.permission.v1.PermissionCreateReply\".\xbaG\x0e\x12\f创建权限\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/permission\x12\x93\x01\n" +
	"\x06Update\x12*.api.permission.v1.PermissionUpdateRequest\x1a(.api.permission.v1.PermissionUpdateReply\"3\xbaG\x0e\x12\f更新权限\x82\xd3\xe4\x93\x02\x1c:\x01*\x1a\x17/api/v1/permission/{id}\x12\x90\x01\n" +
	"\x06Delete\x12*.api.permission.v1.PermissionDeleteRequest\x1a(.api.permission.v1.PermissionDeleteReply\"0\xbaG\x0e\x12\f删除权限\x82\xd3\xe4\x93\x02\x19*\x17/api/v1/permission/{id}BZ\n" +
	"\x11api.permission.v1P\x01ZCgithub.com/sober-studio/bubble-admin-go-kratos/api/permission/v1;v1b\x06proto3"

var (
	file_permission_v1_permission_proto_rawDescOnce sync.Once
	file_permission_v1_permission_proto_rawDescData []byte
)

func file_permission_v1_permission_proto_rawDescGZIP() []byte {
	file_permission_v1_permission_proto_rawDescOnce.Do(func() {
		file_permission_v1_permission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_permission_v1_permission_proto_rawDesc), len(file_permission_v1_permission_proto_rawDesc)))
	})
	return file_permission_v1_permission_proto_rawDescData
}

var file_permission_v1_permission_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_permission_v1_permission_proto_goTypes = []any{
	(*PermissionTreeRequest)(nil),   // 0: api.permission.v1.PermissionTreeRequest
	(*PermissionTreeReply)(nil),     // 1: api.permission.v1.PermissionTreeReply
	(*PermissionGetRequest)(nil),    // 2: api.permission.v1.PermissionGetRequest
	(*PermissionGetReply)(nil),      // 3: api.permission.v1.PermissionGetReply
	(*PermissionCreateRequest)(nil), // 4: api.permission.v1.PermissionCreateRequest
	(*PermissionCreateReply)(nil),   // 5: api.permission.v1.PermissionCreateReply
	(*PermissionUpdateRequest)(nil), // 6: api.permission.v1.PermissionUpdateRequest
	(*PermissionUpdateReply)(nil),   // 7: api.permission.v1.PermissionUpdateReply
	(*PermissionDeleteRequest)(nil), // 8: api.permission.v1.PermissionDeleteRequest
	(*PermissionDeleteReply)(nil),   // 9: api.permission.v1.PermissionDeleteReply
	(*PermissionEntity)(nil),        // 10: api.permission.v1.PermissionEntity
}
var file_permission_v1_permission_proto_depIdxs = []int32{
	10, // 0: api.permission.v1.PermissionTreeReply.list:type_name -> api.permission.v1.PermissionEntity
	10, // 1: api.permission.v1.PermissionGetReply.permission:type_name -> api.permission.v1.PermissionEntity
	10, // 2: api.permission.v1.PermissionEntity.children:type_name -> api.permission.v1.PermissionEntity
	0,  // 3: api.permission.v1.Permission.Tree:input_type -> api.permission.v1.PermissionTreeRequest
	2,  // 4: api.permission.v1.Permission.Get:input_type -> api.permission.v1.PermissionGetRequest
	4,  // 5: api.permission.v1.Permission.Create:input_type -> api.permission.v1.PermissionCreateRequest
	6,  // 6: api.permission.v1.Permission.Update:input_type -> api.permission.v1.PermissionUpdateRequest
	8,  // 7: api.permission.v1.Permission.Delete:input_type -> api.permission.v1.PermissionDeleteRequest
	1,  // 8: api.permission.v1.Permission.Tree:output_type -> api.permission.v1.PermissionTreeReply
	3,  // 9: api.permission.v1.Permission.Get:output_type -> api.permission.v1.PermissionGetReply
	5,  // 10: api.permission.v1.Permission.Create:output_type -> api.permission.v1.PermissionCreateReply
	7,  // 11: api.permission.v1.Permission.Update:output_type -> api.permission.v1.PermissionUpdateReply
	9,  // 12: api.permission.v1.Permission.Delete:output_type -> api.permission.v1.PermissionDeleteReply
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_permission_v1_permission_proto_init() }
func file_permission_v1_permission_proto_init() {
	if File_permission_v1_permission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_permission_v1_permission_proto_rawDesc), len(file_permission_v1_permission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_permission_v1_permission_proto_goTypes,
		DependencyIndexes: file_permission_v1_permission_proto_depIdxs,
		MessageInfos:      file_permission_v1_permission_proto_msgTypes,
	}.Build()
	File_permission_v1_permission_proto = out.File
	file_permission_v1_permission_proto_goTypes = nil
	file_permission_v1_permission_proto_depIdxs = nil
}
