// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.2
// source: permission/v1/permission.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationPermissionCreate = "/api.permission.v1.Permission/Create"
const OperationPermissionDelete = "/api.permission.v1.Permission/Delete"
const OperationPermissionGet = "/api.permission.v1.Permission/Get"
const OperationPermissionTree = "/api.permission.v1.Permission/Tree"
const OperationPermissionUpdate = "/api.permission.v1.Permission/Update"

type PermissionHTTPServer interface {
	// Create 创建权限
	Create(context.Context, *PermissionCreateRequest) (*PermissionCreateReply, error)
	// Delete 删除权限
	Delete(context.Context, *PermissionDeleteRequest) (*PermissionDeleteReply, error)
	// Get 获取权限详情
	Get(context.Context, *PermissionGetRequest) (*PermissionGetReply, error)
	// Tree 获取权限树
	Tree(context.Context, *PermissionTreeRequest) (*PermissionTreeReply, error)
	// Update 更新权限
	Update(context.Context, *PermissionUpdateRequest) (*PermissionUpdateReply, error)
}

func RegisterPermissionHTTPServer(s *http.Server, srv PermissionHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/permission/tree", _Permission_Tree0_HTTP_Handler(srv))
	r.GET("/api/v1/permission/{id}", _Permission_Get4_HTTP_Handler(srv))
	r.POST("/api/v1/permission", _Permission_Create4_HTTP_Handler(srv))
	r.PUT("/api/v1/permission/{id}", _Permission_Update4_HTTP_Handler(srv))
	r.DELETE("/api/v1/permission/{id}", _Permission_Delete4_HTTP_Handler(srv))
}

func _Permission_Tree0_HTTP_Handler(srv PermissionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PermissionTreeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPermissionTree)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Tree(ctx, req.(*PermissionTreeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PermissionTreeReply)
		return ctx.Result(200, reply)
	}
}

func _Permission_Get4_HTTP_Handler(srv PermissionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PermissionGetRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPermissionGet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Get(ctx, req.(*PermissionGetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PermissionGetReply)
		return ctx.Result(200, reply)
	}
}

func _Permission_Create4_HTTP_Handler(srv PermissionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PermissionCreateRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPermissionCreate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Create(ctx, req.(*PermissionCreateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PermissionCreateReply)
		return ctx.Result(200, reply)
	}
}

func _Permission_Update4_HTTP_Handler(srv PermissionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PermissionUpdateRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPermissionUpdate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Update(ctx, req.(*PermissionUpdateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PermissionUpdateReply)
		return ctx.Result(200, reply)
	}
}

func _Permission_Delete4_HTTP_Handler(srv PermissionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PermissionDeleteRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPermissionDelete)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Delete(ctx, req.(*PermissionDeleteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PermissionDeleteReply)
		return ctx.Result(200, reply)
	}
}

type PermissionHTTPClient interface {
	// Create 创建权限
	Create(ctx context.Context, req *PermissionCreateRequest, opts ...http.CallOption) (rsp *PermissionCreateReply, err error)
	// Delete 删除权限
	Delete(ctx context.Context, req *PermissionDeleteRequest, opts ...http.CallOption) (rsp *PermissionDeleteReply, err error)
	// Get 获取权限详情
	Get(ctx context.Context, req *PermissionGetRequest, opts ...http.CallOption) (rsp *PermissionGetReply, err error)
	// Tree 获取权限树
	Tree(ctx context.Context, req *PermissionTreeRequest, opts ...http.CallOption) (rsp *PermissionTreeReply, err error)
	// Update 更新权限
	Update(ctx context.Context, req *PermissionUpdateRequest, opts ...http.CallOption) (rsp *PermissionUpdateReply, err error)
}

type PermissionHTTPClientImpl struct {
	cc *http.Client
}

func NewPermissionHTTPClient(client *http.Client) PermissionHTTPClient {
	return &PermissionHTTPClientImpl{client}
}

// Create 创建权限
func (c *PermissionHTTPClientImpl) Create(ctx context.Context, in *PermissionCreateRequest, opts ...http.CallOption) (*PermissionCreateReply, error) {
	var out PermissionCreateReply
	pattern := "/api/v1/permission"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPermissionCreate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete 删除权限
func (c *PermissionHTTPClientImpl) Delete(ctx context.Context, in *PermissionDeleteRequest, opts ...http.CallOption) (*PermissionDeleteReply, error) {
	var out PermissionDeleteReply
	pattern := "/api/v1/permission/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPermissionDelete))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Get 获取权限详情
func (c *PermissionHTTPClientImpl) Get(ctx context.Context, in *PermissionGetRequest, opts ...http.CallOption) (*PermissionGetReply, error) {
	var out PermissionGetReply
	pattern := "/api/v1/permission/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPermissionGet))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Tree 获取权限树
func (c *PermissionHTTPClientImpl) Tree(ctx context.Context, in *PermissionTreeRequest, opts ...http.CallOption) (*PermissionTreeReply, error) {
	var out PermissionTreeReply
	pattern := "/api/v1/permission/tree"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPermissionTree))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Update 更新权限
func (c *PermissionHTTPClientImpl) Update(ctx context.Context, in *PermissionUpdateRequest, opts ...http.CallOption) (*PermissionUpdateReply, error) {
	var out PermissionUpdateReply
	pattern := "/api/v1/permission/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPermissionUpdate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
