// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/sober-studio/bubble-admin-go-kratos/internal/data/model"
)

func newSysTenant(db *gorm.DB, opts ...gen.DOOption) sysTenant {
	_sysTenant := sysTenant{}

	_sysTenant.sysTenantDo.UseDB(db, opts...)
	_sysTenant.sysTenantDo.UseModel(&model.SysTenant{})

	tableName := _sysTenant.sysTenantDo.TableName()
	_sysTenant.ALL = field.NewAsterisk(tableName)
	_sysTenant.ID = field.NewInt64(tableName, "id")
	_sysTenant.CreatedAt = field.NewTime(tableName, "created_at")
	_sysTenant.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sysTenant.DeletedAt = field.NewField(tableName, "deleted_at")
	_sysTenant.Code = field.NewString(tableName, "code")
	_sysTenant.Name = field.NewString(tableName, "name")
	_sysTenant.PackageID = field.NewInt64(tableName, "package_id")
	_sysTenant.ExpireTime = field.NewTime(tableName, "expire_time")
	_sysTenant.Status = field.NewInt16(tableName, "status")

	_sysTenant.fillFieldMap()

	return _sysTenant
}

type sysTenant struct {
	sysTenantDo

	ALL        field.Asterisk
	ID         field.Int64
	CreatedAt  field.Time
	UpdatedAt  field.Time
	DeletedAt  field.Field
	Code       field.String
	Name       field.String
	PackageID  field.Int64
	ExpireTime field.Time
	Status     field.Int16

	fieldMap map[string]field.Expr
}

func (s sysTenant) Table(newTableName string) *sysTenant {
	s.sysTenantDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysTenant) As(alias string) *sysTenant {
	s.sysTenantDo.DO = *(s.sysTenantDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysTenant) updateTableName(table string) *sysTenant {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")
	s.Code = field.NewString(table, "code")
	s.Name = field.NewString(table, "name")
	s.PackageID = field.NewInt64(table, "package_id")
	s.ExpireTime = field.NewTime(table, "expire_time")
	s.Status = field.NewInt16(table, "status")

	s.fillFieldMap()

	return s
}

func (s *sysTenant) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysTenant) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 9)
	s.fieldMap["id"] = s.ID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["code"] = s.Code
	s.fieldMap["name"] = s.Name
	s.fieldMap["package_id"] = s.PackageID
	s.fieldMap["expire_time"] = s.ExpireTime
	s.fieldMap["status"] = s.Status
}

func (s sysTenant) clone(db *gorm.DB) sysTenant {
	s.sysTenantDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysTenant) replaceDB(db *gorm.DB) sysTenant {
	s.sysTenantDo.ReplaceDB(db)
	return s
}

type sysTenantDo struct{ gen.DO }

type ISysTenantDo interface {
	gen.SubQuery
	Debug() ISysTenantDo
	WithContext(ctx context.Context) ISysTenantDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysTenantDo
	WriteDB() ISysTenantDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysTenantDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysTenantDo
	Not(conds ...gen.Condition) ISysTenantDo
	Or(conds ...gen.Condition) ISysTenantDo
	Select(conds ...field.Expr) ISysTenantDo
	Where(conds ...gen.Condition) ISysTenantDo
	Order(conds ...field.Expr) ISysTenantDo
	Distinct(cols ...field.Expr) ISysTenantDo
	Omit(cols ...field.Expr) ISysTenantDo
	Join(table schema.Tabler, on ...field.Expr) ISysTenantDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysTenantDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysTenantDo
	Group(cols ...field.Expr) ISysTenantDo
	Having(conds ...gen.Condition) ISysTenantDo
	Limit(limit int) ISysTenantDo
	Offset(offset int) ISysTenantDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysTenantDo
	Unscoped() ISysTenantDo
	Create(values ...*model.SysTenant) error
	CreateInBatches(values []*model.SysTenant, batchSize int) error
	Save(values ...*model.SysTenant) error
	First() (*model.SysTenant, error)
	Take() (*model.SysTenant, error)
	Last() (*model.SysTenant, error)
	Find() ([]*model.SysTenant, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysTenant, err error)
	FindInBatches(result *[]*model.SysTenant, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysTenant) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysTenantDo
	Assign(attrs ...field.AssignExpr) ISysTenantDo
	Joins(fields ...field.RelationField) ISysTenantDo
	Preload(fields ...field.RelationField) ISysTenantDo
	FirstOrInit() (*model.SysTenant, error)
	FirstOrCreate() (*model.SysTenant, error)
	FindByPage(offset int, limit int) (result []*model.SysTenant, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysTenantDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysTenantDo) Debug() ISysTenantDo {
	return s.withDO(s.DO.Debug())
}

func (s sysTenantDo) WithContext(ctx context.Context) ISysTenantDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysTenantDo) ReadDB() ISysTenantDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysTenantDo) WriteDB() ISysTenantDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysTenantDo) Session(config *gorm.Session) ISysTenantDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysTenantDo) Clauses(conds ...clause.Expression) ISysTenantDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysTenantDo) Returning(value interface{}, columns ...string) ISysTenantDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysTenantDo) Not(conds ...gen.Condition) ISysTenantDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysTenantDo) Or(conds ...gen.Condition) ISysTenantDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysTenantDo) Select(conds ...field.Expr) ISysTenantDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysTenantDo) Where(conds ...gen.Condition) ISysTenantDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysTenantDo) Order(conds ...field.Expr) ISysTenantDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysTenantDo) Distinct(cols ...field.Expr) ISysTenantDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysTenantDo) Omit(cols ...field.Expr) ISysTenantDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysTenantDo) Join(table schema.Tabler, on ...field.Expr) ISysTenantDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysTenantDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysTenantDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysTenantDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysTenantDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysTenantDo) Group(cols ...field.Expr) ISysTenantDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysTenantDo) Having(conds ...gen.Condition) ISysTenantDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysTenantDo) Limit(limit int) ISysTenantDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysTenantDo) Offset(offset int) ISysTenantDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysTenantDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysTenantDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysTenantDo) Unscoped() ISysTenantDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysTenantDo) Create(values ...*model.SysTenant) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysTenantDo) CreateInBatches(values []*model.SysTenant, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysTenantDo) Save(values ...*model.SysTenant) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysTenantDo) First() (*model.SysTenant, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysTenant), nil
	}
}

func (s sysTenantDo) Take() (*model.SysTenant, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysTenant), nil
	}
}

func (s sysTenantDo) Last() (*model.SysTenant, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysTenant), nil
	}
}

func (s sysTenantDo) Find() ([]*model.SysTenant, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysTenant), err
}

func (s sysTenantDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysTenant, err error) {
	buf := make([]*model.SysTenant, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysTenantDo) FindInBatches(result *[]*model.SysTenant, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysTenantDo) Attrs(attrs ...field.AssignExpr) ISysTenantDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysTenantDo) Assign(attrs ...field.AssignExpr) ISysTenantDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysTenantDo) Joins(fields ...field.RelationField) ISysTenantDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysTenantDo) Preload(fields ...field.RelationField) ISysTenantDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysTenantDo) FirstOrInit() (*model.SysTenant, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysTenant), nil
	}
}

func (s sysTenantDo) FirstOrCreate() (*model.SysTenant, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysTenant), nil
	}
}

func (s sysTenantDo) FindByPage(offset int, limit int) (result []*model.SysTenant, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysTenantDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysTenantDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysTenantDo) Delete(models ...*model.SysTenant) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysTenantDo) withDO(do gen.Dao) *sysTenantDo {
	s.DO = *do.(*gen.DO)
	return s
}
