// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/sober-studio/bubble-admin-go-kratos/internal/data/model"
)

func newSysPermission(db *gorm.DB, opts ...gen.DOOption) sysPermission {
	_sysPermission := sysPermission{}

	_sysPermission.sysPermissionDo.UseDB(db, opts...)
	_sysPermission.sysPermissionDo.UseModel(&model.SysPermission{})

	tableName := _sysPermission.sysPermissionDo.TableName()
	_sysPermission.ALL = field.NewAsterisk(tableName)
	_sysPermission.ID = field.NewInt64(tableName, "id")
	_sysPermission.CreatedAt = field.NewTime(tableName, "created_at")
	_sysPermission.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sysPermission.DeletedAt = field.NewField(tableName, "deleted_at")
	_sysPermission.ParentID = field.NewInt64(tableName, "parent_id")
	_sysPermission.Name = field.NewString(tableName, "name")
	_sysPermission.Code = field.NewString(tableName, "code")
	_sysPermission.Type = field.NewString(tableName, "type")
	_sysPermission.APIPath = field.NewString(tableName, "api_path")
	_sysPermission.APIMethod = field.NewString(tableName, "api_method")
	_sysPermission.Sort = field.NewInt32(tableName, "sort")

	_sysPermission.fillFieldMap()

	return _sysPermission
}

type sysPermission struct {
	sysPermissionDo

	ALL       field.Asterisk
	ID        field.Int64
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	ParentID  field.Int64
	Name      field.String
	Code      field.String
	Type      field.String
	APIPath   field.String
	APIMethod field.String
	Sort      field.Int32

	fieldMap map[string]field.Expr
}

func (s sysPermission) Table(newTableName string) *sysPermission {
	s.sysPermissionDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysPermission) As(alias string) *sysPermission {
	s.sysPermissionDo.DO = *(s.sysPermissionDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysPermission) updateTableName(table string) *sysPermission {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")
	s.ParentID = field.NewInt64(table, "parent_id")
	s.Name = field.NewString(table, "name")
	s.Code = field.NewString(table, "code")
	s.Type = field.NewString(table, "type")
	s.APIPath = field.NewString(table, "api_path")
	s.APIMethod = field.NewString(table, "api_method")
	s.Sort = field.NewInt32(table, "sort")

	s.fillFieldMap()

	return s
}

func (s *sysPermission) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysPermission) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 11)
	s.fieldMap["id"] = s.ID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["parent_id"] = s.ParentID
	s.fieldMap["name"] = s.Name
	s.fieldMap["code"] = s.Code
	s.fieldMap["type"] = s.Type
	s.fieldMap["api_path"] = s.APIPath
	s.fieldMap["api_method"] = s.APIMethod
	s.fieldMap["sort"] = s.Sort
}

func (s sysPermission) clone(db *gorm.DB) sysPermission {
	s.sysPermissionDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysPermission) replaceDB(db *gorm.DB) sysPermission {
	s.sysPermissionDo.ReplaceDB(db)
	return s
}

type sysPermissionDo struct{ gen.DO }

type ISysPermissionDo interface {
	gen.SubQuery
	Debug() ISysPermissionDo
	WithContext(ctx context.Context) ISysPermissionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysPermissionDo
	WriteDB() ISysPermissionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysPermissionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysPermissionDo
	Not(conds ...gen.Condition) ISysPermissionDo
	Or(conds ...gen.Condition) ISysPermissionDo
	Select(conds ...field.Expr) ISysPermissionDo
	Where(conds ...gen.Condition) ISysPermissionDo
	Order(conds ...field.Expr) ISysPermissionDo
	Distinct(cols ...field.Expr) ISysPermissionDo
	Omit(cols ...field.Expr) ISysPermissionDo
	Join(table schema.Tabler, on ...field.Expr) ISysPermissionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysPermissionDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysPermissionDo
	Group(cols ...field.Expr) ISysPermissionDo
	Having(conds ...gen.Condition) ISysPermissionDo
	Limit(limit int) ISysPermissionDo
	Offset(offset int) ISysPermissionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysPermissionDo
	Unscoped() ISysPermissionDo
	Create(values ...*model.SysPermission) error
	CreateInBatches(values []*model.SysPermission, batchSize int) error
	Save(values ...*model.SysPermission) error
	First() (*model.SysPermission, error)
	Take() (*model.SysPermission, error)
	Last() (*model.SysPermission, error)
	Find() ([]*model.SysPermission, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysPermission, err error)
	FindInBatches(result *[]*model.SysPermission, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysPermission) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysPermissionDo
	Assign(attrs ...field.AssignExpr) ISysPermissionDo
	Joins(fields ...field.RelationField) ISysPermissionDo
	Preload(fields ...field.RelationField) ISysPermissionDo
	FirstOrInit() (*model.SysPermission, error)
	FirstOrCreate() (*model.SysPermission, error)
	FindByPage(offset int, limit int) (result []*model.SysPermission, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysPermissionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysPermissionDo) Debug() ISysPermissionDo {
	return s.withDO(s.DO.Debug())
}

func (s sysPermissionDo) WithContext(ctx context.Context) ISysPermissionDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysPermissionDo) ReadDB() ISysPermissionDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysPermissionDo) WriteDB() ISysPermissionDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysPermissionDo) Session(config *gorm.Session) ISysPermissionDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysPermissionDo) Clauses(conds ...clause.Expression) ISysPermissionDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysPermissionDo) Returning(value interface{}, columns ...string) ISysPermissionDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysPermissionDo) Not(conds ...gen.Condition) ISysPermissionDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysPermissionDo) Or(conds ...gen.Condition) ISysPermissionDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysPermissionDo) Select(conds ...field.Expr) ISysPermissionDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysPermissionDo) Where(conds ...gen.Condition) ISysPermissionDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysPermissionDo) Order(conds ...field.Expr) ISysPermissionDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysPermissionDo) Distinct(cols ...field.Expr) ISysPermissionDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysPermissionDo) Omit(cols ...field.Expr) ISysPermissionDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysPermissionDo) Join(table schema.Tabler, on ...field.Expr) ISysPermissionDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysPermissionDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysPermissionDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysPermissionDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysPermissionDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysPermissionDo) Group(cols ...field.Expr) ISysPermissionDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysPermissionDo) Having(conds ...gen.Condition) ISysPermissionDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysPermissionDo) Limit(limit int) ISysPermissionDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysPermissionDo) Offset(offset int) ISysPermissionDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysPermissionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysPermissionDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysPermissionDo) Unscoped() ISysPermissionDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysPermissionDo) Create(values ...*model.SysPermission) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysPermissionDo) CreateInBatches(values []*model.SysPermission, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysPermissionDo) Save(values ...*model.SysPermission) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysPermissionDo) First() (*model.SysPermission, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysPermission), nil
	}
}

func (s sysPermissionDo) Take() (*model.SysPermission, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysPermission), nil
	}
}

func (s sysPermissionDo) Last() (*model.SysPermission, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysPermission), nil
	}
}

func (s sysPermissionDo) Find() ([]*model.SysPermission, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysPermission), err
}

func (s sysPermissionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysPermission, err error) {
	buf := make([]*model.SysPermission, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysPermissionDo) FindInBatches(result *[]*model.SysPermission, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysPermissionDo) Attrs(attrs ...field.AssignExpr) ISysPermissionDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysPermissionDo) Assign(attrs ...field.AssignExpr) ISysPermissionDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysPermissionDo) Joins(fields ...field.RelationField) ISysPermissionDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysPermissionDo) Preload(fields ...field.RelationField) ISysPermissionDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysPermissionDo) FirstOrInit() (*model.SysPermission, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysPermission), nil
	}
}

func (s sysPermissionDo) FirstOrCreate() (*model.SysPermission, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysPermission), nil
	}
}

func (s sysPermissionDo) FindByPage(offset int, limit int) (result []*model.SysPermission, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysPermissionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysPermissionDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysPermissionDo) Delete(models ...*model.SysPermission) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysPermissionDo) withDO(do gen.Dao) *sysPermissionDo {
	s.DO = *do.(*gen.DO)
	return s
}
