// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/sober-studio/bubble-admin-go-kratos/internal/data/model"
)

func newSysPackagePermission(db *gorm.DB, opts ...gen.DOOption) sysPackagePermission {
	_sysPackagePermission := sysPackagePermission{}

	_sysPackagePermission.sysPackagePermissionDo.UseDB(db, opts...)
	_sysPackagePermission.sysPackagePermissionDo.UseModel(&model.SysPackagePermission{})

	tableName := _sysPackagePermission.sysPackagePermissionDo.TableName()
	_sysPackagePermission.ALL = field.NewAsterisk(tableName)
	_sysPackagePermission.ID = field.NewInt64(tableName, "id")
	_sysPackagePermission.PackageID = field.NewInt64(tableName, "package_id")
	_sysPackagePermission.PermissionID = field.NewInt64(tableName, "permission_id")
	_sysPackagePermission.CreatedAt = field.NewTime(tableName, "created_at")

	_sysPackagePermission.fillFieldMap()

	return _sysPackagePermission
}

type sysPackagePermission struct {
	sysPackagePermissionDo

	ALL          field.Asterisk
	ID           field.Int64
	PackageID    field.Int64
	PermissionID field.Int64
	CreatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (s sysPackagePermission) Table(newTableName string) *sysPackagePermission {
	s.sysPackagePermissionDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysPackagePermission) As(alias string) *sysPackagePermission {
	s.sysPackagePermissionDo.DO = *(s.sysPackagePermissionDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysPackagePermission) updateTableName(table string) *sysPackagePermission {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.PackageID = field.NewInt64(table, "package_id")
	s.PermissionID = field.NewInt64(table, "permission_id")
	s.CreatedAt = field.NewTime(table, "created_at")

	s.fillFieldMap()

	return s
}

func (s *sysPackagePermission) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysPackagePermission) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 4)
	s.fieldMap["id"] = s.ID
	s.fieldMap["package_id"] = s.PackageID
	s.fieldMap["permission_id"] = s.PermissionID
	s.fieldMap["created_at"] = s.CreatedAt
}

func (s sysPackagePermission) clone(db *gorm.DB) sysPackagePermission {
	s.sysPackagePermissionDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysPackagePermission) replaceDB(db *gorm.DB) sysPackagePermission {
	s.sysPackagePermissionDo.ReplaceDB(db)
	return s
}

type sysPackagePermissionDo struct{ gen.DO }

type ISysPackagePermissionDo interface {
	gen.SubQuery
	Debug() ISysPackagePermissionDo
	WithContext(ctx context.Context) ISysPackagePermissionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysPackagePermissionDo
	WriteDB() ISysPackagePermissionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysPackagePermissionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysPackagePermissionDo
	Not(conds ...gen.Condition) ISysPackagePermissionDo
	Or(conds ...gen.Condition) ISysPackagePermissionDo
	Select(conds ...field.Expr) ISysPackagePermissionDo
	Where(conds ...gen.Condition) ISysPackagePermissionDo
	Order(conds ...field.Expr) ISysPackagePermissionDo
	Distinct(cols ...field.Expr) ISysPackagePermissionDo
	Omit(cols ...field.Expr) ISysPackagePermissionDo
	Join(table schema.Tabler, on ...field.Expr) ISysPackagePermissionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysPackagePermissionDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysPackagePermissionDo
	Group(cols ...field.Expr) ISysPackagePermissionDo
	Having(conds ...gen.Condition) ISysPackagePermissionDo
	Limit(limit int) ISysPackagePermissionDo
	Offset(offset int) ISysPackagePermissionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysPackagePermissionDo
	Unscoped() ISysPackagePermissionDo
	Create(values ...*model.SysPackagePermission) error
	CreateInBatches(values []*model.SysPackagePermission, batchSize int) error
	Save(values ...*model.SysPackagePermission) error
	First() (*model.SysPackagePermission, error)
	Take() (*model.SysPackagePermission, error)
	Last() (*model.SysPackagePermission, error)
	Find() ([]*model.SysPackagePermission, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysPackagePermission, err error)
	FindInBatches(result *[]*model.SysPackagePermission, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysPackagePermission) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysPackagePermissionDo
	Assign(attrs ...field.AssignExpr) ISysPackagePermissionDo
	Joins(fields ...field.RelationField) ISysPackagePermissionDo
	Preload(fields ...field.RelationField) ISysPackagePermissionDo
	FirstOrInit() (*model.SysPackagePermission, error)
	FirstOrCreate() (*model.SysPackagePermission, error)
	FindByPage(offset int, limit int) (result []*model.SysPackagePermission, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysPackagePermissionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysPackagePermissionDo) Debug() ISysPackagePermissionDo {
	return s.withDO(s.DO.Debug())
}

func (s sysPackagePermissionDo) WithContext(ctx context.Context) ISysPackagePermissionDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysPackagePermissionDo) ReadDB() ISysPackagePermissionDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysPackagePermissionDo) WriteDB() ISysPackagePermissionDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysPackagePermissionDo) Session(config *gorm.Session) ISysPackagePermissionDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysPackagePermissionDo) Clauses(conds ...clause.Expression) ISysPackagePermissionDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysPackagePermissionDo) Returning(value interface{}, columns ...string) ISysPackagePermissionDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysPackagePermissionDo) Not(conds ...gen.Condition) ISysPackagePermissionDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysPackagePermissionDo) Or(conds ...gen.Condition) ISysPackagePermissionDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysPackagePermissionDo) Select(conds ...field.Expr) ISysPackagePermissionDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysPackagePermissionDo) Where(conds ...gen.Condition) ISysPackagePermissionDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysPackagePermissionDo) Order(conds ...field.Expr) ISysPackagePermissionDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysPackagePermissionDo) Distinct(cols ...field.Expr) ISysPackagePermissionDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysPackagePermissionDo) Omit(cols ...field.Expr) ISysPackagePermissionDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysPackagePermissionDo) Join(table schema.Tabler, on ...field.Expr) ISysPackagePermissionDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysPackagePermissionDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysPackagePermissionDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysPackagePermissionDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysPackagePermissionDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysPackagePermissionDo) Group(cols ...field.Expr) ISysPackagePermissionDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysPackagePermissionDo) Having(conds ...gen.Condition) ISysPackagePermissionDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysPackagePermissionDo) Limit(limit int) ISysPackagePermissionDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysPackagePermissionDo) Offset(offset int) ISysPackagePermissionDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysPackagePermissionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysPackagePermissionDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysPackagePermissionDo) Unscoped() ISysPackagePermissionDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysPackagePermissionDo) Create(values ...*model.SysPackagePermission) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysPackagePermissionDo) CreateInBatches(values []*model.SysPackagePermission, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysPackagePermissionDo) Save(values ...*model.SysPackagePermission) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysPackagePermissionDo) First() (*model.SysPackagePermission, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysPackagePermission), nil
	}
}

func (s sysPackagePermissionDo) Take() (*model.SysPackagePermission, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysPackagePermission), nil
	}
}

func (s sysPackagePermissionDo) Last() (*model.SysPackagePermission, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysPackagePermission), nil
	}
}

func (s sysPackagePermissionDo) Find() ([]*model.SysPackagePermission, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysPackagePermission), err
}

func (s sysPackagePermissionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysPackagePermission, err error) {
	buf := make([]*model.SysPackagePermission, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysPackagePermissionDo) FindInBatches(result *[]*model.SysPackagePermission, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysPackagePermissionDo) Attrs(attrs ...field.AssignExpr) ISysPackagePermissionDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysPackagePermissionDo) Assign(attrs ...field.AssignExpr) ISysPackagePermissionDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysPackagePermissionDo) Joins(fields ...field.RelationField) ISysPackagePermissionDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysPackagePermissionDo) Preload(fields ...field.RelationField) ISysPackagePermissionDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysPackagePermissionDo) FirstOrInit() (*model.SysPackagePermission, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysPackagePermission), nil
	}
}

func (s sysPackagePermissionDo) FirstOrCreate() (*model.SysPackagePermission, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysPackagePermission), nil
	}
}

func (s sysPackagePermissionDo) FindByPage(offset int, limit int) (result []*model.SysPackagePermission, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysPackagePermissionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysPackagePermissionDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysPackagePermissionDo) Delete(models ...*model.SysPackagePermission) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysPackagePermissionDo) withDO(do gen.Dao) *sysPackagePermissionDo {
	s.DO = *do.(*gen.DO)
	return s
}
