// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/sober-studio/bubble-admin-go-kratos/internal/data/model"
)

func newSysRolePermission(db *gorm.DB, opts ...gen.DOOption) sysRolePermission {
	_sysRolePermission := sysRolePermission{}

	_sysRolePermission.sysRolePermissionDo.UseDB(db, opts...)
	_sysRolePermission.sysRolePermissionDo.UseModel(&model.SysRolePermission{})

	tableName := _sysRolePermission.sysRolePermissionDo.TableName()
	_sysRolePermission.ALL = field.NewAsterisk(tableName)
	_sysRolePermission.ID = field.NewInt64(tableName, "id")
	_sysRolePermission.CreatedAt = field.NewTime(tableName, "created_at")
	_sysRolePermission.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sysRolePermission.DeletedAt = field.NewField(tableName, "deleted_at")
	_sysRolePermission.RoleID = field.NewInt64(tableName, "role_id")
	_sysRolePermission.PermissionID = field.NewInt64(tableName, "permission_id")
	_sysRolePermission.DataScope = field.NewString(tableName, "data_scope")
	_sysRolePermission.TenantID = field.NewInt64(tableName, "tenant_id")

	_sysRolePermission.fillFieldMap()

	return _sysRolePermission
}

type sysRolePermission struct {
	sysRolePermissionDo

	ALL          field.Asterisk
	ID           field.Int64
	CreatedAt    field.Time
	UpdatedAt    field.Time
	DeletedAt    field.Field
	RoleID       field.Int64
	PermissionID field.Int64
	DataScope    field.String
	TenantID     field.Int64

	fieldMap map[string]field.Expr
}

func (s sysRolePermission) Table(newTableName string) *sysRolePermission {
	s.sysRolePermissionDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysRolePermission) As(alias string) *sysRolePermission {
	s.sysRolePermissionDo.DO = *(s.sysRolePermissionDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysRolePermission) updateTableName(table string) *sysRolePermission {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")
	s.RoleID = field.NewInt64(table, "role_id")
	s.PermissionID = field.NewInt64(table, "permission_id")
	s.DataScope = field.NewString(table, "data_scope")
	s.TenantID = field.NewInt64(table, "tenant_id")

	s.fillFieldMap()

	return s
}

func (s *sysRolePermission) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysRolePermission) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 8)
	s.fieldMap["id"] = s.ID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["role_id"] = s.RoleID
	s.fieldMap["permission_id"] = s.PermissionID
	s.fieldMap["data_scope"] = s.DataScope
	s.fieldMap["tenant_id"] = s.TenantID
}

func (s sysRolePermission) clone(db *gorm.DB) sysRolePermission {
	s.sysRolePermissionDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysRolePermission) replaceDB(db *gorm.DB) sysRolePermission {
	s.sysRolePermissionDo.ReplaceDB(db)
	return s
}

type sysRolePermissionDo struct{ gen.DO }

type ISysRolePermissionDo interface {
	gen.SubQuery
	Debug() ISysRolePermissionDo
	WithContext(ctx context.Context) ISysRolePermissionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysRolePermissionDo
	WriteDB() ISysRolePermissionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysRolePermissionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysRolePermissionDo
	Not(conds ...gen.Condition) ISysRolePermissionDo
	Or(conds ...gen.Condition) ISysRolePermissionDo
	Select(conds ...field.Expr) ISysRolePermissionDo
	Where(conds ...gen.Condition) ISysRolePermissionDo
	Order(conds ...field.Expr) ISysRolePermissionDo
	Distinct(cols ...field.Expr) ISysRolePermissionDo
	Omit(cols ...field.Expr) ISysRolePermissionDo
	Join(table schema.Tabler, on ...field.Expr) ISysRolePermissionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysRolePermissionDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysRolePermissionDo
	Group(cols ...field.Expr) ISysRolePermissionDo
	Having(conds ...gen.Condition) ISysRolePermissionDo
	Limit(limit int) ISysRolePermissionDo
	Offset(offset int) ISysRolePermissionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysRolePermissionDo
	Unscoped() ISysRolePermissionDo
	Create(values ...*model.SysRolePermission) error
	CreateInBatches(values []*model.SysRolePermission, batchSize int) error
	Save(values ...*model.SysRolePermission) error
	First() (*model.SysRolePermission, error)
	Take() (*model.SysRolePermission, error)
	Last() (*model.SysRolePermission, error)
	Find() ([]*model.SysRolePermission, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysRolePermission, err error)
	FindInBatches(result *[]*model.SysRolePermission, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysRolePermission) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysRolePermissionDo
	Assign(attrs ...field.AssignExpr) ISysRolePermissionDo
	Joins(fields ...field.RelationField) ISysRolePermissionDo
	Preload(fields ...field.RelationField) ISysRolePermissionDo
	FirstOrInit() (*model.SysRolePermission, error)
	FirstOrCreate() (*model.SysRolePermission, error)
	FindByPage(offset int, limit int) (result []*model.SysRolePermission, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysRolePermissionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysRolePermissionDo) Debug() ISysRolePermissionDo {
	return s.withDO(s.DO.Debug())
}

func (s sysRolePermissionDo) WithContext(ctx context.Context) ISysRolePermissionDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysRolePermissionDo) ReadDB() ISysRolePermissionDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysRolePermissionDo) WriteDB() ISysRolePermissionDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysRolePermissionDo) Session(config *gorm.Session) ISysRolePermissionDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysRolePermissionDo) Clauses(conds ...clause.Expression) ISysRolePermissionDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysRolePermissionDo) Returning(value interface{}, columns ...string) ISysRolePermissionDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysRolePermissionDo) Not(conds ...gen.Condition) ISysRolePermissionDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysRolePermissionDo) Or(conds ...gen.Condition) ISysRolePermissionDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysRolePermissionDo) Select(conds ...field.Expr) ISysRolePermissionDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysRolePermissionDo) Where(conds ...gen.Condition) ISysRolePermissionDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysRolePermissionDo) Order(conds ...field.Expr) ISysRolePermissionDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysRolePermissionDo) Distinct(cols ...field.Expr) ISysRolePermissionDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysRolePermissionDo) Omit(cols ...field.Expr) ISysRolePermissionDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysRolePermissionDo) Join(table schema.Tabler, on ...field.Expr) ISysRolePermissionDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysRolePermissionDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysRolePermissionDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysRolePermissionDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysRolePermissionDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysRolePermissionDo) Group(cols ...field.Expr) ISysRolePermissionDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysRolePermissionDo) Having(conds ...gen.Condition) ISysRolePermissionDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysRolePermissionDo) Limit(limit int) ISysRolePermissionDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysRolePermissionDo) Offset(offset int) ISysRolePermissionDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysRolePermissionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysRolePermissionDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysRolePermissionDo) Unscoped() ISysRolePermissionDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysRolePermissionDo) Create(values ...*model.SysRolePermission) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysRolePermissionDo) CreateInBatches(values []*model.SysRolePermission, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysRolePermissionDo) Save(values ...*model.SysRolePermission) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysRolePermissionDo) First() (*model.SysRolePermission, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRolePermission), nil
	}
}

func (s sysRolePermissionDo) Take() (*model.SysRolePermission, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRolePermission), nil
	}
}

func (s sysRolePermissionDo) Last() (*model.SysRolePermission, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRolePermission), nil
	}
}

func (s sysRolePermissionDo) Find() ([]*model.SysRolePermission, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysRolePermission), err
}

func (s sysRolePermissionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysRolePermission, err error) {
	buf := make([]*model.SysRolePermission, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysRolePermissionDo) FindInBatches(result *[]*model.SysRolePermission, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysRolePermissionDo) Attrs(attrs ...field.AssignExpr) ISysRolePermissionDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysRolePermissionDo) Assign(attrs ...field.AssignExpr) ISysRolePermissionDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysRolePermissionDo) Joins(fields ...field.RelationField) ISysRolePermissionDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysRolePermissionDo) Preload(fields ...field.RelationField) ISysRolePermissionDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysRolePermissionDo) FirstOrInit() (*model.SysRolePermission, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRolePermission), nil
	}
}

func (s sysRolePermissionDo) FirstOrCreate() (*model.SysRolePermission, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRolePermission), nil
	}
}

func (s sysRolePermissionDo) FindByPage(offset int, limit int) (result []*model.SysRolePermission, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysRolePermissionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysRolePermissionDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysRolePermissionDo) Delete(models ...*model.SysRolePermission) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysRolePermissionDo) withDO(do gen.Dao) *sysRolePermissionDo {
	s.DO = *do.(*gen.DO)
	return s
}
