// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/dept/v1/dept.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on DeptListRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DeptListRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeptListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeptListRequestMultiError, or nil if none found.
func (m *DeptListRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeptListRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Status

	if len(errors) > 0 {
		return DeptListRequestMultiError(errors)
	}

	return nil
}

// DeptListRequestMultiError is an error wrapping multiple validation errors
// returned by DeptListRequest.ValidateAll() if the designated constraints
// aren't met.
type DeptListRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeptListRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeptListRequestMultiError) AllErrors() []error { return m }

// DeptListRequestValidationError is the validation error returned by
// DeptListRequest.Validate if the designated constraints aren't met.
type DeptListRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeptListRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeptListRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeptListRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeptListRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeptListRequestValidationError) ErrorName() string { return "DeptListRequestValidationError" }

// Error satisfies the builtin error interface
func (e DeptListRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeptListRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeptListRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeptListRequestValidationError{}

// Validate checks the field values on DeptListReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DeptListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeptListReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DeptListReplyMultiError, or
// nil if none found.
func (m *DeptListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *DeptListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DeptListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DeptListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DeptListReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return DeptListReplyMultiError(errors)
	}

	return nil
}

// DeptListReplyMultiError is an error wrapping multiple validation errors
// returned by DeptListReply.ValidateAll() if the designated constraints
// aren't met.
type DeptListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeptListReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeptListReplyMultiError) AllErrors() []error { return m }

// DeptListReplyValidationError is the validation error returned by
// DeptListReply.Validate if the designated constraints aren't met.
type DeptListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeptListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeptListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeptListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeptListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeptListReplyValidationError) ErrorName() string { return "DeptListReplyValidationError" }

// Error satisfies the builtin error interface
func (e DeptListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeptListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeptListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeptListReplyValidationError{}

// Validate checks the field values on DeptGetRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DeptGetRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeptGetRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DeptGetRequestMultiError,
// or nil if none found.
func (m *DeptGetRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeptGetRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return DeptGetRequestMultiError(errors)
	}

	return nil
}

// DeptGetRequestMultiError is an error wrapping multiple validation errors
// returned by DeptGetRequest.ValidateAll() if the designated constraints
// aren't met.
type DeptGetRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeptGetRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeptGetRequestMultiError) AllErrors() []error { return m }

// DeptGetRequestValidationError is the validation error returned by
// DeptGetRequest.Validate if the designated constraints aren't met.
type DeptGetRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeptGetRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeptGetRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeptGetRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeptGetRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeptGetRequestValidationError) ErrorName() string { return "DeptGetRequestValidationError" }

// Error satisfies the builtin error interface
func (e DeptGetRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeptGetRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeptGetRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeptGetRequestValidationError{}

// Validate checks the field values on DeptGetReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DeptGetReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeptGetReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DeptGetReplyMultiError, or
// nil if none found.
func (m *DeptGetReply) ValidateAll() error {
	return m.validate(true)
}

func (m *DeptGetReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetDept()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DeptGetReplyValidationError{
					field:  "Dept",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DeptGetReplyValidationError{
					field:  "Dept",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDept()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DeptGetReplyValidationError{
				field:  "Dept",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return DeptGetReplyMultiError(errors)
	}

	return nil
}

// DeptGetReplyMultiError is an error wrapping multiple validation errors
// returned by DeptGetReply.ValidateAll() if the designated constraints aren't met.
type DeptGetReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeptGetReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeptGetReplyMultiError) AllErrors() []error { return m }

// DeptGetReplyValidationError is the validation error returned by
// DeptGetReply.Validate if the designated constraints aren't met.
type DeptGetReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeptGetReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeptGetReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeptGetReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeptGetReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeptGetReplyValidationError) ErrorName() string { return "DeptGetReplyValidationError" }

// Error satisfies the builtin error interface
func (e DeptGetReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeptGetReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeptGetReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeptGetReplyValidationError{}

// Validate checks the field values on DeptCreateRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DeptCreateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeptCreateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeptCreateRequestMultiError, or nil if none found.
func (m *DeptCreateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeptCreateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ParentId

	// no validation rules for Name

	// no validation rules for Sort

	if len(errors) > 0 {
		return DeptCreateRequestMultiError(errors)
	}

	return nil
}

// DeptCreateRequestMultiError is an error wrapping multiple validation errors
// returned by DeptCreateRequest.ValidateAll() if the designated constraints
// aren't met.
type DeptCreateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeptCreateRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeptCreateRequestMultiError) AllErrors() []error { return m }

// DeptCreateRequestValidationError is the validation error returned by
// DeptCreateRequest.Validate if the designated constraints aren't met.
type DeptCreateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeptCreateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeptCreateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeptCreateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeptCreateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeptCreateRequestValidationError) ErrorName() string {
	return "DeptCreateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeptCreateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeptCreateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeptCreateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeptCreateRequestValidationError{}

// Validate checks the field values on DeptCreateReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DeptCreateReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeptCreateReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeptCreateReplyMultiError, or nil if none found.
func (m *DeptCreateReply) ValidateAll() error {
	return m.validate(true)
}

func (m *DeptCreateReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return DeptCreateReplyMultiError(errors)
	}

	return nil
}

// DeptCreateReplyMultiError is an error wrapping multiple validation errors
// returned by DeptCreateReply.ValidateAll() if the designated constraints
// aren't met.
type DeptCreateReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeptCreateReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeptCreateReplyMultiError) AllErrors() []error { return m }

// DeptCreateReplyValidationError is the validation error returned by
// DeptCreateReply.Validate if the designated constraints aren't met.
type DeptCreateReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeptCreateReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeptCreateReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeptCreateReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeptCreateReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeptCreateReplyValidationError) ErrorName() string { return "DeptCreateReplyValidationError" }

// Error satisfies the builtin error interface
func (e DeptCreateReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeptCreateReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeptCreateReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeptCreateReplyValidationError{}

// Validate checks the field values on DeptUpdateRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DeptUpdateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeptUpdateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeptUpdateRequestMultiError, or nil if none found.
func (m *DeptUpdateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeptUpdateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for ParentId

	// no validation rules for Name

	// no validation rules for Sort

	if len(errors) > 0 {
		return DeptUpdateRequestMultiError(errors)
	}

	return nil
}

// DeptUpdateRequestMultiError is an error wrapping multiple validation errors
// returned by DeptUpdateRequest.ValidateAll() if the designated constraints
// aren't met.
type DeptUpdateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeptUpdateRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeptUpdateRequestMultiError) AllErrors() []error { return m }

// DeptUpdateRequestValidationError is the validation error returned by
// DeptUpdateRequest.Validate if the designated constraints aren't met.
type DeptUpdateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeptUpdateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeptUpdateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeptUpdateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeptUpdateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeptUpdateRequestValidationError) ErrorName() string {
	return "DeptUpdateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeptUpdateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeptUpdateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeptUpdateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeptUpdateRequestValidationError{}

// Validate checks the field values on DeptUpdateReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DeptUpdateReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeptUpdateReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeptUpdateReplyMultiError, or nil if none found.
func (m *DeptUpdateReply) ValidateAll() error {
	return m.validate(true)
}

func (m *DeptUpdateReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeptUpdateReplyMultiError(errors)
	}

	return nil
}

// DeptUpdateReplyMultiError is an error wrapping multiple validation errors
// returned by DeptUpdateReply.ValidateAll() if the designated constraints
// aren't met.
type DeptUpdateReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeptUpdateReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeptUpdateReplyMultiError) AllErrors() []error { return m }

// DeptUpdateReplyValidationError is the validation error returned by
// DeptUpdateReply.Validate if the designated constraints aren't met.
type DeptUpdateReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeptUpdateReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeptUpdateReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeptUpdateReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeptUpdateReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeptUpdateReplyValidationError) ErrorName() string { return "DeptUpdateReplyValidationError" }

// Error satisfies the builtin error interface
func (e DeptUpdateReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeptUpdateReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeptUpdateReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeptUpdateReplyValidationError{}

// Validate checks the field values on DeptDeleteRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DeptDeleteRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeptDeleteRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeptDeleteRequestMultiError, or nil if none found.
func (m *DeptDeleteRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeptDeleteRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return DeptDeleteRequestMultiError(errors)
	}

	return nil
}

// DeptDeleteRequestMultiError is an error wrapping multiple validation errors
// returned by DeptDeleteRequest.ValidateAll() if the designated constraints
// aren't met.
type DeptDeleteRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeptDeleteRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeptDeleteRequestMultiError) AllErrors() []error { return m }

// DeptDeleteRequestValidationError is the validation error returned by
// DeptDeleteRequest.Validate if the designated constraints aren't met.
type DeptDeleteRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeptDeleteRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeptDeleteRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeptDeleteRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeptDeleteRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeptDeleteRequestValidationError) ErrorName() string {
	return "DeptDeleteRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeptDeleteRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeptDeleteRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeptDeleteRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeptDeleteRequestValidationError{}

// Validate checks the field values on DeptDeleteReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DeptDeleteReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeptDeleteReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeptDeleteReplyMultiError, or nil if none found.
func (m *DeptDeleteReply) ValidateAll() error {
	return m.validate(true)
}

func (m *DeptDeleteReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeptDeleteReplyMultiError(errors)
	}

	return nil
}

// DeptDeleteReplyMultiError is an error wrapping multiple validation errors
// returned by DeptDeleteReply.ValidateAll() if the designated constraints
// aren't met.
type DeptDeleteReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeptDeleteReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeptDeleteReplyMultiError) AllErrors() []error { return m }

// DeptDeleteReplyValidationError is the validation error returned by
// DeptDeleteReply.Validate if the designated constraints aren't met.
type DeptDeleteReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeptDeleteReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeptDeleteReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeptDeleteReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeptDeleteReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeptDeleteReplyValidationError) ErrorName() string { return "DeptDeleteReplyValidationError" }

// Error satisfies the builtin error interface
func (e DeptDeleteReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeptDeleteReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeptDeleteReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeptDeleteReplyValidationError{}

// Validate checks the field values on DeptEntity with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DeptEntity) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeptEntity with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DeptEntityMultiError, or
// nil if none found.
func (m *DeptEntity) ValidateAll() error {
	return m.validate(true)
}

func (m *DeptEntity) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for ParentId

	// no validation rules for Name

	// no validation rules for Ancestors

	// no validation rules for Sort

	// no validation rules for CreatedAt

	for idx, item := range m.GetChildren() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DeptEntityValidationError{
						field:  fmt.Sprintf("Children[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DeptEntityValidationError{
						field:  fmt.Sprintf("Children[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DeptEntityValidationError{
					field:  fmt.Sprintf("Children[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return DeptEntityMultiError(errors)
	}

	return nil
}

// DeptEntityMultiError is an error wrapping multiple validation errors
// returned by DeptEntity.ValidateAll() if the designated constraints aren't met.
type DeptEntityMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeptEntityMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeptEntityMultiError) AllErrors() []error { return m }

// DeptEntityValidationError is the validation error returned by
// DeptEntity.Validate if the designated constraints aren't met.
type DeptEntityValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeptEntityValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeptEntityValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeptEntityValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeptEntityValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeptEntityValidationError) ErrorName() string { return "DeptEntityValidationError" }

// Error satisfies the builtin error interface
func (e DeptEntityValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeptEntity.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeptEntityValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeptEntityValidationError{}
