// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: dept/v1/dept.proto

package v1

import (
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ========== 部门列表 ==========
type DeptListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 部门名称（模糊查询）
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 状态：0=禁用，1=正常
	Status        int32 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeptListRequest) Reset() {
	*x = DeptListRequest{}
	mi := &file_dept_v1_dept_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeptListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptListRequest) ProtoMessage() {}

func (x *DeptListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dept_v1_dept_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptListRequest.ProtoReflect.Descriptor instead.
func (*DeptListRequest) Descriptor() ([]byte, []int) {
	return file_dept_v1_dept_proto_rawDescGZIP(), []int{0}
}

func (x *DeptListRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeptListRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type DeptListReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 部门列表
	List          []*DeptEntity `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeptListReply) Reset() {
	*x = DeptListReply{}
	mi := &file_dept_v1_dept_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeptListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptListReply) ProtoMessage() {}

func (x *DeptListReply) ProtoReflect() protoreflect.Message {
	mi := &file_dept_v1_dept_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptListReply.ProtoReflect.Descriptor instead.
func (*DeptListReply) Descriptor() ([]byte, []int) {
	return file_dept_v1_dept_proto_rawDescGZIP(), []int{1}
}

func (x *DeptListReply) GetList() []*DeptEntity {
	if x != nil {
		return x.List
	}
	return nil
}

// ========== 部门详情 ==========
type DeptGetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 部门ID
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeptGetRequest) Reset() {
	*x = DeptGetRequest{}
	mi := &file_dept_v1_dept_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeptGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptGetRequest) ProtoMessage() {}

func (x *DeptGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dept_v1_dept_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptGetRequest.ProtoReflect.Descriptor instead.
func (*DeptGetRequest) Descriptor() ([]byte, []int) {
	return file_dept_v1_dept_proto_rawDescGZIP(), []int{2}
}

func (x *DeptGetRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeptGetReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 部门信息
	Dept          *DeptEntity `protobuf:"bytes,1,opt,name=dept,proto3" json:"dept,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeptGetReply) Reset() {
	*x = DeptGetReply{}
	mi := &file_dept_v1_dept_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeptGetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptGetReply) ProtoMessage() {}

func (x *DeptGetReply) ProtoReflect() protoreflect.Message {
	mi := &file_dept_v1_dept_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptGetReply.ProtoReflect.Descriptor instead.
func (*DeptGetReply) Descriptor() ([]byte, []int) {
	return file_dept_v1_dept_proto_rawDescGZIP(), []int{3}
}

func (x *DeptGetReply) GetDept() *DeptEntity {
	if x != nil {
		return x.Dept
	}
	return nil
}

// ========== 创建部门 ==========
type DeptCreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 父部门ID
	ParentId int64 `protobuf:"varint,1,opt,name=parent_id,proto3" json:"parent_id,omitempty"`
	// 部门名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 排序序号
	Sort int32 `protobuf:"varint,3,opt,name=sort,proto3" json:"sort,omitempty"`
	// 负责人用户ID
	LeaderUserId int64 `protobuf:"varint,4,opt,name=leader_user_id,proto3" json:"leader_user_id,omitempty"`
	// 负责人姓名
	LeaderUserName string `protobuf:"bytes,5,opt,name=leader_user_name,proto3" json:"leader_user_name,omitempty"`
	// 联系电话
	Phone string `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	// 邮箱
	Email string `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	// 状态：0=禁用，1=正常
	Status        int32 `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeptCreateRequest) Reset() {
	*x = DeptCreateRequest{}
	mi := &file_dept_v1_dept_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeptCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptCreateRequest) ProtoMessage() {}

func (x *DeptCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dept_v1_dept_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptCreateRequest.ProtoReflect.Descriptor instead.
func (*DeptCreateRequest) Descriptor() ([]byte, []int) {
	return file_dept_v1_dept_proto_rawDescGZIP(), []int{4}
}

func (x *DeptCreateRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *DeptCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeptCreateRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *DeptCreateRequest) GetLeaderUserId() int64 {
	if x != nil {
		return x.LeaderUserId
	}
	return 0
}

func (x *DeptCreateRequest) GetLeaderUserName() string {
	if x != nil {
		return x.LeaderUserName
	}
	return ""
}

func (x *DeptCreateRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *DeptCreateRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *DeptCreateRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type DeptCreateReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 部门ID
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeptCreateReply) Reset() {
	*x = DeptCreateReply{}
	mi := &file_dept_v1_dept_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeptCreateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptCreateReply) ProtoMessage() {}

func (x *DeptCreateReply) ProtoReflect() protoreflect.Message {
	mi := &file_dept_v1_dept_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptCreateReply.ProtoReflect.Descriptor instead.
func (*DeptCreateReply) Descriptor() ([]byte, []int) {
	return file_dept_v1_dept_proto_rawDescGZIP(), []int{5}
}

func (x *DeptCreateReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// ========== 更新部门 ==========
type DeptUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 部门ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 父部门ID
	ParentId int64 `protobuf:"varint,2,opt,name=parent_id,proto3" json:"parent_id,omitempty"`
	// 部门名称
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// 排序序号
	Sort int32 `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	// 负责人用户ID
	LeaderUserId int64 `protobuf:"varint,5,opt,name=leader_user_id,proto3" json:"leader_user_id,omitempty"`
	// 负责人姓名
	LeaderUserName string `protobuf:"bytes,6,opt,name=leader_user_name,proto3" json:"leader_user_name,omitempty"`
	// 联系电话
	Phone string `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	// 邮箱
	Email string `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	// 状态：0=禁用，1=正常
	Status        int32 `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeptUpdateRequest) Reset() {
	*x = DeptUpdateRequest{}
	mi := &file_dept_v1_dept_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeptUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptUpdateRequest) ProtoMessage() {}

func (x *DeptUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dept_v1_dept_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptUpdateRequest.ProtoReflect.Descriptor instead.
func (*DeptUpdateRequest) Descriptor() ([]byte, []int) {
	return file_dept_v1_dept_proto_rawDescGZIP(), []int{6}
}

func (x *DeptUpdateRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeptUpdateRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *DeptUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeptUpdateRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *DeptUpdateRequest) GetLeaderUserId() int64 {
	if x != nil {
		return x.LeaderUserId
	}
	return 0
}

func (x *DeptUpdateRequest) GetLeaderUserName() string {
	if x != nil {
		return x.LeaderUserName
	}
	return ""
}

func (x *DeptUpdateRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *DeptUpdateRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *DeptUpdateRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type DeptUpdateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeptUpdateReply) Reset() {
	*x = DeptUpdateReply{}
	mi := &file_dept_v1_dept_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeptUpdateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptUpdateReply) ProtoMessage() {}

func (x *DeptUpdateReply) ProtoReflect() protoreflect.Message {
	mi := &file_dept_v1_dept_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptUpdateReply.ProtoReflect.Descriptor instead.
func (*DeptUpdateReply) Descriptor() ([]byte, []int) {
	return file_dept_v1_dept_proto_rawDescGZIP(), []int{7}
}

// ========== 删除部门 ==========
type DeptDeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 部门ID
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeptDeleteRequest) Reset() {
	*x = DeptDeleteRequest{}
	mi := &file_dept_v1_dept_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeptDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptDeleteRequest) ProtoMessage() {}

func (x *DeptDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dept_v1_dept_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptDeleteRequest.ProtoReflect.Descriptor instead.
func (*DeptDeleteRequest) Descriptor() ([]byte, []int) {
	return file_dept_v1_dept_proto_rawDescGZIP(), []int{8}
}

func (x *DeptDeleteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeptDeleteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeptDeleteReply) Reset() {
	*x = DeptDeleteReply{}
	mi := &file_dept_v1_dept_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeptDeleteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptDeleteReply) ProtoMessage() {}

func (x *DeptDeleteReply) ProtoReflect() protoreflect.Message {
	mi := &file_dept_v1_dept_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptDeleteReply.ProtoReflect.Descriptor instead.
func (*DeptDeleteReply) Descriptor() ([]byte, []int) {
	return file_dept_v1_dept_proto_rawDescGZIP(), []int{9}
}

// ========== 部门实体 ==========
type DeptEntity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 部门ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 父部门ID
	ParentId int64 `protobuf:"varint,2,opt,name=parent_id,proto3" json:"parent_id,omitempty"`
	// 部门名称
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// 祖先路径
	Ancestors string `protobuf:"bytes,4,opt,name=ancestors,proto3" json:"ancestors,omitempty"`
	// 排序序号
	Sort int32 `protobuf:"varint,5,opt,name=sort,proto3" json:"sort,omitempty"`
	// 负责人用户ID
	LeaderUserId int64 `protobuf:"varint,6,opt,name=leader_user_id,proto3" json:"leader_user_id,omitempty"`
	// 负责人姓名
	LeaderUserName string `protobuf:"bytes,7,opt,name=leader_user_name,proto3" json:"leader_user_name,omitempty"`
	// 联系电话
	Phone string `protobuf:"bytes,8,opt,name=phone,proto3" json:"phone,omitempty"`
	// 邮箱
	Email string `protobuf:"bytes,9,opt,name=email,proto3" json:"email,omitempty"`
	// 状态：0=禁用，1=正常
	Status int32 `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	// 创建时间
	CreatedAt int64 `protobuf:"varint,11,opt,name=created_at,proto3" json:"created_at,omitempty"`
	// 子部门
	Children      []*DeptEntity `protobuf:"bytes,12,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeptEntity) Reset() {
	*x = DeptEntity{}
	mi := &file_dept_v1_dept_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeptEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptEntity) ProtoMessage() {}

func (x *DeptEntity) ProtoReflect() protoreflect.Message {
	mi := &file_dept_v1_dept_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptEntity.ProtoReflect.Descriptor instead.
func (*DeptEntity) Descriptor() ([]byte, []int) {
	return file_dept_v1_dept_proto_rawDescGZIP(), []int{10}
}

func (x *DeptEntity) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeptEntity) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *DeptEntity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeptEntity) GetAncestors() string {
	if x != nil {
		return x.Ancestors
	}
	return ""
}

func (x *DeptEntity) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *DeptEntity) GetLeaderUserId() int64 {
	if x != nil {
		return x.LeaderUserId
	}
	return 0
}

func (x *DeptEntity) GetLeaderUserName() string {
	if x != nil {
		return x.LeaderUserName
	}
	return ""
}

func (x *DeptEntity) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *DeptEntity) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *DeptEntity) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DeptEntity) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *DeptEntity) GetChildren() []*DeptEntity {
	if x != nil {
		return x.Children
	}
	return nil
}

var File_dept_v1_dept_proto protoreflect.FileDescriptor

const file_dept_v1_dept_proto_rawDesc = "" +
	"\n" +
	"\x12dept/v1/dept.proto\x12\vapi.dept.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1copenapi/v3/annotations.proto\"\x87\x01\n" +
	"\x0fDeptListRequest\x128\n" +
	"\x04name\x18\x01 \x01(\tB$\xbaG!\x92\x02\x1e部门名称（模糊查询）R\x04name\x12:\n" +
	"\x06status\x18\x02 \x01(\x05B\"\xbaG\x1f\x92\x02\x1c状态：0=禁用，1=正常R\x06status\"P\n" +
	"\rDeptListReply\x12?\n" +
	"\x04list\x18\x01 \x03(\v2\x17.api.dept.v1.DeptEntityB\x12\xbaG\x0f\x92\x02\f部门列表R\x04list\"4\n" +
	"\x0eDeptGetRequest\x12\"\n" +
	"\x02id\x18\x01 \x01(\x03B\x12\xe2A\x01\x02\xbaG\v\x92\x02\b部门IDR\x02id\"O\n" +
	"\fDeptGetReply\x12?\n" +
	"\x04dept\x18\x01 \x01(\v2\x17.api.dept.v1.DeptEntityB\x12\xbaG\x0f\x92\x02\f部门信息R\x04dept\"\xa6\x03\n" +
	"\x11DeptCreateRequest\x12/\n" +
	"\tparent_id\x18\x01 \x01(\x03B\x11\xbaG\x0e\x92\x02\v父部门IDR\tparent_id\x12*\n" +
	"\x04name\x18\x02 \x01(\tB\x16\xe2A\x01\x02\xbaG\x0f\x92\x02\f部门名称R\x04name\x12&\n" +
	"\x04sort\x18\x03 \x01(\x05B\x12\xbaG\x0f\x92\x02\f排序序号R\x04sort\x12?\n" +
	"\x0eleader_user_id\x18\x04 \x01(\x03B\x17\xbaG\x14\x92\x02\x11负责人用户IDR\x0eleader_user_id\x12A\n" +
	"\x10leader_user_name\x18\x05 \x01(\tB\x15\xbaG\x12\x92\x02\x0f负责人姓名R\x10leader_user_name\x12(\n" +
	"\x05phone\x18\x06 \x01(\tB\x12\xbaG\x0f\x92\x02\f联系电话R\x05phone\x12\"\n" +
	"\x05email\x18\a \x01(\tB\f\xbaG\t\x92\x02\x06邮箱R\x05email\x12:\n" +
	"\x06status\x18\b \x01(\x05B\"\xbaG\x1f\x92\x02\x1c状态：0=禁用，1=正常R\x06status\"1\n" +
	"\x0fDeptCreateReply\x12\x1e\n" +
	"\x02id\x18\x01 \x01(\x03B\x0e\xbaG\v\x92\x02\b部门IDR\x02id\"\xca\x03\n" +
	"\x11DeptUpdateRequest\x12\"\n" +
	"\x02id\x18\x01 \x01(\x03B\x12\xe2A\x01\x02\xbaG\v\x92\x02\b部门IDR\x02id\x12/\n" +
	"\tparent_id\x18\x02 \x01(\x03B\x11\xbaG\x0e\x92\x02\v父部门IDR\tparent_id\x12*\n" +
	"\x04name\x18\x03 \x01(\tB\x16\xe2A\x01\x02\xbaG\x0f\x92\x02\f部门名称R\x04name\x12&\n" +
	"\x04sort\x18\x04 \x01(\x05B\x12\xbaG\x0f\x92\x02\f排序序号R\x04sort\x12?\n" +
	"\x0eleader_user_id\x18\x05 \x01(\x03B\x17\xbaG\x14\x92\x02\x11负责人用户IDR\x0eleader_user_id\x12A\n" +
	"\x10leader_user_name\x18\x06 \x01(\tB\x15\xbaG\x12\x92\x02\x0f负责人姓名R\x10leader_user_name\x12(\n" +
	"\x05phone\x18\a \x01(\tB\x12\xbaG\x0f\x92\x02\f联系电话R\x05phone\x12\"\n" +
	"\x05email\x18\b \x01(\tB\f\xbaG\t\x92\x02\x06邮箱R\x05email\x12:\n" +
	"\x06status\x18\t \x01(\x05B\"\xbaG\x1f\x92\x02\x1c状态：0=禁用，1=正常R\x06status\"\x11\n" +
	"\x0fDeptUpdateReply\"7\n" +
	"\x11DeptDeleteRequest\x12\"\n" +
	"\x02id\x18\x01 \x01(\x03B\x12\xe2A\x01\x02\xbaG\v\x92\x02\b部门IDR\x02id\"\x11\n" +
	"\x0fDeptDeleteReply\"\xe7\x04\n" +
	"\n" +
	"DeptEntity\x12\x1e\n" +
	"\x02id\x18\x01 \x01(\x03B\x0e\xbaG\v\x92\x02\b部门IDR\x02id\x12/\n" +
	"\tparent_id\x18\x02 \x01(\x03B\x11\xbaG\x0e\x92\x02\v父部门IDR\tparent_id\x12&\n" +
	"\x04name\x18\x03 \x01(\tB\x12\xbaG\x0f\x92\x02\f部门名称R\x04name\x120\n" +
	"\tancestors\x18\x04 \x01(\tB\x12\xbaG\x0f\x92\x02\f祖先路径R\tancestors\x12&\n" +
	"\x04sort\x18\x05 \x01(\x05B\x12\xbaG\x0f\x92\x02\f排序序号R\x04sort\x12?\n" +
	"\x0eleader_user_id\x18\x06 \x01(\x03B\x17\xbaG\x14\x92\x02\x11负责人用户IDR\x0eleader_user_id\x12A\n" +
	"\x10leader_user_name\x18\a \x01(\tB\x15\xbaG\x12\x92\x02\x0f负责人姓名R\x10leader_user_name\x12(\n" +
	"\x05phone\x18\b \x01(\tB\x12\xbaG\x0f\x92\x02\f联系电话R\x05phone\x12\"\n" +
	"\x05email\x18\t \x01(\tB\f\xbaG\t\x92\x02\x06邮箱R\x05email\x12:\n" +
	"\x06status\x18\n" +
	" \x01(\x05B\"\xbaG\x1f\x92\x02\x1c状态：0=禁用，1=正常R\x06status\x122\n" +
	"\n" +
	"created_at\x18\v \x01(\x03B\x12\xbaG\x0f\x92\x02\f创建时间R\n" +
	"created_at\x12D\n" +
	"\bchildren\x18\f \x03(\v2\x17.api.dept.v1.DeptEntityB\x0f\xbaG\f\x92\x02\t子部门R\bchildren2\xc8\x04\n" +
	"\x04Dept\x12r\n" +
	"\x04List\x12\x1c.api.dept.v1.DeptListRequest\x1a\x1a.api.dept.v1.DeptListReply\"0\xbaG\x14\x12\x12获取部门列表\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/dept/list\x12o\n" +
	"\x03Get\x12\x1b.api.dept.v1.DeptGetRequest\x1a\x19.api.dept.v1.DeptGetReply\"0\xbaG\x14\x12\x12获取部门详情\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/dept/{id}\x12p\n" +
	"\x06Create\x12\x1e.api.dept.v1.DeptCreateRequest\x1a\x1c.api.dept.v1.DeptCreateReply\"(\xbaG\x0e\x12\f创建部门\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/api/v1/dept\x12u\n" +
	"\x06Update\x12\x1e.api.dept.v1.DeptUpdateRequest\x1a\x1c.api.dept.v1.DeptUpdateReply\"-\xbaG\x0e\x12\f更新部门\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/api/v1/dept/{id}\x12r\n" +
	"\x06Delete\x12\x1e.api.dept.v1.DeptDeleteRequest\x1a\x1c.api.dept.v1.DeptDeleteReply\"*\xbaG\x0e\x12\f删除部门\x82\xd3\xe4\x93\x02\x13*\x11/api/v1/dept/{id}BN\n" +
	"\vapi.dept.v1P\x01Z=github.com/sober-studio/bubble-admin-go-kratos/api/dept/v1;v1b\x06proto3"

var (
	file_dept_v1_dept_proto_rawDescOnce sync.Once
	file_dept_v1_dept_proto_rawDescData []byte
)

func file_dept_v1_dept_proto_rawDescGZIP() []byte {
	file_dept_v1_dept_proto_rawDescOnce.Do(func() {
		file_dept_v1_dept_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dept_v1_dept_proto_rawDesc), len(file_dept_v1_dept_proto_rawDesc)))
	})
	return file_dept_v1_dept_proto_rawDescData
}

var file_dept_v1_dept_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_dept_v1_dept_proto_goTypes = []any{
	(*DeptListRequest)(nil),   // 0: api.dept.v1.DeptListRequest
	(*DeptListReply)(nil),     // 1: api.dept.v1.DeptListReply
	(*DeptGetRequest)(nil),    // 2: api.dept.v1.DeptGetRequest
	(*DeptGetReply)(nil),      // 3: api.dept.v1.DeptGetReply
	(*DeptCreateRequest)(nil), // 4: api.dept.v1.DeptCreateRequest
	(*DeptCreateReply)(nil),   // 5: api.dept.v1.DeptCreateReply
	(*DeptUpdateRequest)(nil), // 6: api.dept.v1.DeptUpdateRequest
	(*DeptUpdateReply)(nil),   // 7: api.dept.v1.DeptUpdateReply
	(*DeptDeleteRequest)(nil), // 8: api.dept.v1.DeptDeleteRequest
	(*DeptDeleteReply)(nil),   // 9: api.dept.v1.DeptDeleteReply
	(*DeptEntity)(nil),        // 10: api.dept.v1.DeptEntity
}
var file_dept_v1_dept_proto_depIdxs = []int32{
	10, // 0: api.dept.v1.DeptListReply.list:type_name -> api.dept.v1.DeptEntity
	10, // 1: api.dept.v1.DeptGetReply.dept:type_name -> api.dept.v1.DeptEntity
	10, // 2: api.dept.v1.DeptEntity.children:type_name -> api.dept.v1.DeptEntity
	0,  // 3: api.dept.v1.Dept.List:input_type -> api.dept.v1.DeptListRequest
	2,  // 4: api.dept.v1.Dept.Get:input_type -> api.dept.v1.DeptGetRequest
	4,  // 5: api.dept.v1.Dept.Create:input_type -> api.dept.v1.DeptCreateRequest
	6,  // 6: api.dept.v1.Dept.Update:input_type -> api.dept.v1.DeptUpdateRequest
	8,  // 7: api.dept.v1.Dept.Delete:input_type -> api.dept.v1.DeptDeleteRequest
	1,  // 8: api.dept.v1.Dept.List:output_type -> api.dept.v1.DeptListReply
	3,  // 9: api.dept.v1.Dept.Get:output_type -> api.dept.v1.DeptGetReply
	5,  // 10: api.dept.v1.Dept.Create:output_type -> api.dept.v1.DeptCreateReply
	7,  // 11: api.dept.v1.Dept.Update:output_type -> api.dept.v1.DeptUpdateReply
	9,  // 12: api.dept.v1.Dept.Delete:output_type -> api.dept.v1.DeptDeleteReply
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_dept_v1_dept_proto_init() }
func file_dept_v1_dept_proto_init() {
	if File_dept_v1_dept_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dept_v1_dept_proto_rawDesc), len(file_dept_v1_dept_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dept_v1_dept_proto_goTypes,
		DependencyIndexes: file_dept_v1_dept_proto_depIdxs,
		MessageInfos:      file_dept_v1_dept_proto_msgTypes,
	}.Build()
	File_dept_v1_dept_proto = out.File
	file_dept_v1_dept_proto_goTypes = nil
	file_dept_v1_dept_proto_depIdxs = nil
}
