// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysTenant = "sys_tenant"

// SysTenant mapped from table <sys_tenant>
type SysTenant struct {
	Code       string     `gorm:"column:code;type:character varying(64);not null" json:"code"`
	Name       string     `gorm:"column:name;type:character varying(128);not null" json:"name"`
	PackageID  *int64     `gorm:"column:package_id;type:bigint" json:"package_id"`
	ExpireTime *time.Time `gorm:"column:expire_time;type:timestamp with time zone" json:"expire_time"`
	Status     *int16     `gorm:"column:status;type:smallint;default:1" json:"status"`
	BaseModel  `gorm:"embedded"`
}

// TableName SysTenant's table name
func (*SysTenant) TableName() string {
	return TableNameSysTenant
}
