// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysRolePermission = "sys_role_permission"

// SysRolePermission mapped from table <sys_role_permission>
type SysRolePermission struct {
	ID           int64      `gorm:"column:id;type:bigint;primaryKey" json:"id"`
	TenantID     int64      `gorm:"column:tenant_id;type:bigint;not null" json:"tenant_id"`
	RoleID       int64      `gorm:"column:role_id;type:bigint;not null" json:"role_id"`
	PermissionID int64      `gorm:"column:permission_id;type:bigint;not null" json:"permission_id"`
	DataScope    *string    `gorm:"column:data_scope;type:character varying(20);default:SELF;comment:数据范围: SELF(个人), DEPT(本部门), DEPT_SUB(本部门及下级), ALL(全租户)" json:"data_scope"` // 数据范围: SELF(个人), DEPT(本部门), DEPT_SUB(本部门及下级), ALL(全租户)
	CreatedAt    *time.Time `gorm:"column:created_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName SysRolePermission's table name
func (*SysRolePermission) TableName() string {
	return TableNameSysRolePermission
}
