// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysUser = "sys_user"

// SysUser mapped from table <sys_user>
type SysUser struct {
	TenantID     int64   `gorm:"column:tenant_id;type:bigint;not null" json:"tenant_id"`
	DeptID       *int64  `gorm:"column:dept_id;type:bigint" json:"dept_id"`
	Username     string  `gorm:"column:username;type:character varying(64);not null" json:"username"`
	PasswordHash string  `gorm:"column:password_hash;type:character varying(255);not null" json:"password_hash"`
	Name         *string `gorm:"column:name;type:character varying(64)" json:"name"`
	Mobile       *string `gorm:"column:mobile;type:character varying(20)" json:"mobile"`
	Status       *int16  `gorm:"column:status;type:smallint;default:1" json:"status"`
	BaseModel    `gorm:"embedded"`
}

// TableName SysUser's table name
func (*SysUser) TableName() string {
	return TableNameSysUser
}
