// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysPackage = "sys_package"

// SysPackage mapped from table <sys_package>
type SysPackage struct {
	Name      string  `gorm:"column:name;type:character varying(128);not null" json:"name"`
	Status    *int16  `gorm:"column:status;type:smallint;default:1" json:"status"`
	Remark    *string `gorm:"column:remark;type:character varying(255)" json:"remark"`
	BaseModel `gorm:"embedded"`
}

// TableName SysPackage's table name
func (*SysPackage) TableName() string {
	return TableNameSysPackage
}
