// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/tenant/v1/tenant.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on TenantListRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *TenantListRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TenantListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TenantListRequestMultiError, or nil if none found.
func (m *TenantListRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *TenantListRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Code

	// no validation rules for Status

	// no validation rules for Page

	// no validation rules for PageSize

	if len(errors) > 0 {
		return TenantListRequestMultiError(errors)
	}

	return nil
}

// TenantListRequestMultiError is an error wrapping multiple validation errors
// returned by TenantListRequest.ValidateAll() if the designated constraints
// aren't met.
type TenantListRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TenantListRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TenantListRequestMultiError) AllErrors() []error { return m }

// TenantListRequestValidationError is the validation error returned by
// TenantListRequest.Validate if the designated constraints aren't met.
type TenantListRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TenantListRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TenantListRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TenantListRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TenantListRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TenantListRequestValidationError) ErrorName() string {
	return "TenantListRequestValidationError"
}

// Error satisfies the builtin error interface
func (e TenantListRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTenantListRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TenantListRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TenantListRequestValidationError{}

// Validate checks the field values on TenantListReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *TenantListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TenantListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TenantListReplyMultiError, or nil if none found.
func (m *TenantListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *TenantListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, TenantListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, TenantListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return TenantListReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return TenantListReplyMultiError(errors)
	}

	return nil
}

// TenantListReplyMultiError is an error wrapping multiple validation errors
// returned by TenantListReply.ValidateAll() if the designated constraints
// aren't met.
type TenantListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TenantListReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TenantListReplyMultiError) AllErrors() []error { return m }

// TenantListReplyValidationError is the validation error returned by
// TenantListReply.Validate if the designated constraints aren't met.
type TenantListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TenantListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TenantListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TenantListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TenantListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TenantListReplyValidationError) ErrorName() string { return "TenantListReplyValidationError" }

// Error satisfies the builtin error interface
func (e TenantListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTenantListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TenantListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TenantListReplyValidationError{}

// Validate checks the field values on TenantGetRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *TenantGetRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TenantGetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TenantGetRequestMultiError, or nil if none found.
func (m *TenantGetRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *TenantGetRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return TenantGetRequestMultiError(errors)
	}

	return nil
}

// TenantGetRequestMultiError is an error wrapping multiple validation errors
// returned by TenantGetRequest.ValidateAll() if the designated constraints
// aren't met.
type TenantGetRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TenantGetRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TenantGetRequestMultiError) AllErrors() []error { return m }

// TenantGetRequestValidationError is the validation error returned by
// TenantGetRequest.Validate if the designated constraints aren't met.
type TenantGetRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TenantGetRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TenantGetRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TenantGetRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TenantGetRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TenantGetRequestValidationError) ErrorName() string { return "TenantGetRequestValidationError" }

// Error satisfies the builtin error interface
func (e TenantGetRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTenantGetRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TenantGetRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TenantGetRequestValidationError{}

// Validate checks the field values on TenantGetReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TenantGetReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TenantGetReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TenantGetReplyMultiError,
// or nil if none found.
func (m *TenantGetReply) ValidateAll() error {
	return m.validate(true)
}

func (m *TenantGetReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetTenant()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TenantGetReplyValidationError{
					field:  "Tenant",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TenantGetReplyValidationError{
					field:  "Tenant",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTenant()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TenantGetReplyValidationError{
				field:  "Tenant",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for PackageId

	// no validation rules for PackageName

	if len(errors) > 0 {
		return TenantGetReplyMultiError(errors)
	}

	return nil
}

// TenantGetReplyMultiError is an error wrapping multiple validation errors
// returned by TenantGetReply.ValidateAll() if the designated constraints
// aren't met.
type TenantGetReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TenantGetReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TenantGetReplyMultiError) AllErrors() []error { return m }

// TenantGetReplyValidationError is the validation error returned by
// TenantGetReply.Validate if the designated constraints aren't met.
type TenantGetReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TenantGetReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TenantGetReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TenantGetReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TenantGetReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TenantGetReplyValidationError) ErrorName() string { return "TenantGetReplyValidationError" }

// Error satisfies the builtin error interface
func (e TenantGetReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTenantGetReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TenantGetReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TenantGetReplyValidationError{}

// Validate checks the field values on TenantCreateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TenantCreateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TenantCreateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TenantCreateRequestMultiError, or nil if none found.
func (m *TenantCreateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *TenantCreateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Code

	// no validation rules for PackageId

	// no validation rules for ExpiredAt

	if len(errors) > 0 {
		return TenantCreateRequestMultiError(errors)
	}

	return nil
}

// TenantCreateRequestMultiError is an error wrapping multiple validation
// errors returned by TenantCreateRequest.ValidateAll() if the designated
// constraints aren't met.
type TenantCreateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TenantCreateRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TenantCreateRequestMultiError) AllErrors() []error { return m }

// TenantCreateRequestValidationError is the validation error returned by
// TenantCreateRequest.Validate if the designated constraints aren't met.
type TenantCreateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TenantCreateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TenantCreateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TenantCreateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TenantCreateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TenantCreateRequestValidationError) ErrorName() string {
	return "TenantCreateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e TenantCreateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTenantCreateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TenantCreateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TenantCreateRequestValidationError{}

// Validate checks the field values on TenantCreateReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *TenantCreateReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TenantCreateReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TenantCreateReplyMultiError, or nil if none found.
func (m *TenantCreateReply) ValidateAll() error {
	return m.validate(true)
}

func (m *TenantCreateReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return TenantCreateReplyMultiError(errors)
	}

	return nil
}

// TenantCreateReplyMultiError is an error wrapping multiple validation errors
// returned by TenantCreateReply.ValidateAll() if the designated constraints
// aren't met.
type TenantCreateReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TenantCreateReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TenantCreateReplyMultiError) AllErrors() []error { return m }

// TenantCreateReplyValidationError is the validation error returned by
// TenantCreateReply.Validate if the designated constraints aren't met.
type TenantCreateReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TenantCreateReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TenantCreateReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TenantCreateReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TenantCreateReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TenantCreateReplyValidationError) ErrorName() string {
	return "TenantCreateReplyValidationError"
}

// Error satisfies the builtin error interface
func (e TenantCreateReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTenantCreateReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TenantCreateReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TenantCreateReplyValidationError{}

// Validate checks the field values on TenantUpdateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TenantUpdateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TenantUpdateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TenantUpdateRequestMultiError, or nil if none found.
func (m *TenantUpdateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *TenantUpdateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Code

	// no validation rules for PackageId

	// no validation rules for ExpiredAt

	if len(errors) > 0 {
		return TenantUpdateRequestMultiError(errors)
	}

	return nil
}

// TenantUpdateRequestMultiError is an error wrapping multiple validation
// errors returned by TenantUpdateRequest.ValidateAll() if the designated
// constraints aren't met.
type TenantUpdateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TenantUpdateRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TenantUpdateRequestMultiError) AllErrors() []error { return m }

// TenantUpdateRequestValidationError is the validation error returned by
// TenantUpdateRequest.Validate if the designated constraints aren't met.
type TenantUpdateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TenantUpdateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TenantUpdateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TenantUpdateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TenantUpdateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TenantUpdateRequestValidationError) ErrorName() string {
	return "TenantUpdateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e TenantUpdateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTenantUpdateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TenantUpdateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TenantUpdateRequestValidationError{}

// Validate checks the field values on TenantUpdateReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *TenantUpdateReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TenantUpdateReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TenantUpdateReplyMultiError, or nil if none found.
func (m *TenantUpdateReply) ValidateAll() error {
	return m.validate(true)
}

func (m *TenantUpdateReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return TenantUpdateReplyMultiError(errors)
	}

	return nil
}

// TenantUpdateReplyMultiError is an error wrapping multiple validation errors
// returned by TenantUpdateReply.ValidateAll() if the designated constraints
// aren't met.
type TenantUpdateReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TenantUpdateReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TenantUpdateReplyMultiError) AllErrors() []error { return m }

// TenantUpdateReplyValidationError is the validation error returned by
// TenantUpdateReply.Validate if the designated constraints aren't met.
type TenantUpdateReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TenantUpdateReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TenantUpdateReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TenantUpdateReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TenantUpdateReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TenantUpdateReplyValidationError) ErrorName() string {
	return "TenantUpdateReplyValidationError"
}

// Error satisfies the builtin error interface
func (e TenantUpdateReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTenantUpdateReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TenantUpdateReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TenantUpdateReplyValidationError{}

// Validate checks the field values on TenantDeleteRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TenantDeleteRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TenantDeleteRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TenantDeleteRequestMultiError, or nil if none found.
func (m *TenantDeleteRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *TenantDeleteRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return TenantDeleteRequestMultiError(errors)
	}

	return nil
}

// TenantDeleteRequestMultiError is an error wrapping multiple validation
// errors returned by TenantDeleteRequest.ValidateAll() if the designated
// constraints aren't met.
type TenantDeleteRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TenantDeleteRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TenantDeleteRequestMultiError) AllErrors() []error { return m }

// TenantDeleteRequestValidationError is the validation error returned by
// TenantDeleteRequest.Validate if the designated constraints aren't met.
type TenantDeleteRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TenantDeleteRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TenantDeleteRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TenantDeleteRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TenantDeleteRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TenantDeleteRequestValidationError) ErrorName() string {
	return "TenantDeleteRequestValidationError"
}

// Error satisfies the builtin error interface
func (e TenantDeleteRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTenantDeleteRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TenantDeleteRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TenantDeleteRequestValidationError{}

// Validate checks the field values on TenantDeleteReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *TenantDeleteReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TenantDeleteReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TenantDeleteReplyMultiError, or nil if none found.
func (m *TenantDeleteReply) ValidateAll() error {
	return m.validate(true)
}

func (m *TenantDeleteReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return TenantDeleteReplyMultiError(errors)
	}

	return nil
}

// TenantDeleteReplyMultiError is an error wrapping multiple validation errors
// returned by TenantDeleteReply.ValidateAll() if the designated constraints
// aren't met.
type TenantDeleteReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TenantDeleteReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TenantDeleteReplyMultiError) AllErrors() []error { return m }

// TenantDeleteReplyValidationError is the validation error returned by
// TenantDeleteReply.Validate if the designated constraints aren't met.
type TenantDeleteReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TenantDeleteReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TenantDeleteReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TenantDeleteReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TenantDeleteReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TenantDeleteReplyValidationError) ErrorName() string {
	return "TenantDeleteReplyValidationError"
}

// Error satisfies the builtin error interface
func (e TenantDeleteReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTenantDeleteReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TenantDeleteReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TenantDeleteReplyValidationError{}

// Validate checks the field values on TenantEntity with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TenantEntity) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TenantEntity with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TenantEntityMultiError, or
// nil if none found.
func (m *TenantEntity) ValidateAll() error {
	return m.validate(true)
}

func (m *TenantEntity) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Code

	// no validation rules for Status

	// no validation rules for ExpiredAt

	// no validation rules for CreatedAt

	if len(errors) > 0 {
		return TenantEntityMultiError(errors)
	}

	return nil
}

// TenantEntityMultiError is an error wrapping multiple validation errors
// returned by TenantEntity.ValidateAll() if the designated constraints aren't met.
type TenantEntityMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TenantEntityMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TenantEntityMultiError) AllErrors() []error { return m }

// TenantEntityValidationError is the validation error returned by
// TenantEntity.Validate if the designated constraints aren't met.
type TenantEntityValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TenantEntityValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TenantEntityValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TenantEntityValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TenantEntityValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TenantEntityValidationError) ErrorName() string { return "TenantEntityValidationError" }

// Error satisfies the builtin error interface
func (e TenantEntityValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTenantEntity.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TenantEntityValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TenantEntityValidationError{}
