// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.2
// source: tenant/v1/tenant.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationTenantCreate = "/api.tenant.v1.Tenant/Create"
const OperationTenantDelete = "/api.tenant.v1.Tenant/Delete"
const OperationTenantGet = "/api.tenant.v1.Tenant/Get"
const OperationTenantList = "/api.tenant.v1.Tenant/List"
const OperationTenantUpdate = "/api.tenant.v1.Tenant/Update"

type TenantHTTPServer interface {
	// Create 创建租户
	Create(context.Context, *TenantCreateRequest) (*TenantCreateReply, error)
	// Delete 删除租户
	Delete(context.Context, *TenantDeleteRequest) (*TenantDeleteReply, error)
	// Get 获取租户详情
	Get(context.Context, *TenantGetRequest) (*TenantGetReply, error)
	// List 获取租户列表
	List(context.Context, *TenantListRequest) (*TenantListReply, error)
	// Update 更新租户
	Update(context.Context, *TenantUpdateRequest) (*TenantUpdateReply, error)
}

func RegisterTenantHTTPServer(s *http.Server, srv TenantHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/tenant/list", _Tenant_List0_HTTP_Handler(srv))
	r.GET("/api/v1/tenant/{id}", _Tenant_Get0_HTTP_Handler(srv))
	r.POST("/api/v1/tenant", _Tenant_Create0_HTTP_Handler(srv))
	r.PUT("/api/v1/tenant/{id}", _Tenant_Update0_HTTP_Handler(srv))
	r.DELETE("/api/v1/tenant/{id}", _Tenant_Delete0_HTTP_Handler(srv))
}

func _Tenant_List0_HTTP_Handler(srv TenantHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TenantListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTenantList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.List(ctx, req.(*TenantListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TenantListReply)
		return ctx.Result(200, reply)
	}
}

func _Tenant_Get0_HTTP_Handler(srv TenantHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TenantGetRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTenantGet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Get(ctx, req.(*TenantGetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TenantGetReply)
		return ctx.Result(200, reply)
	}
}

func _Tenant_Create0_HTTP_Handler(srv TenantHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TenantCreateRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTenantCreate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Create(ctx, req.(*TenantCreateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TenantCreateReply)
		return ctx.Result(200, reply)
	}
}

func _Tenant_Update0_HTTP_Handler(srv TenantHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TenantUpdateRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTenantUpdate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Update(ctx, req.(*TenantUpdateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TenantUpdateReply)
		return ctx.Result(200, reply)
	}
}

func _Tenant_Delete0_HTTP_Handler(srv TenantHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TenantDeleteRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTenantDelete)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Delete(ctx, req.(*TenantDeleteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TenantDeleteReply)
		return ctx.Result(200, reply)
	}
}

type TenantHTTPClient interface {
	// Create 创建租户
	Create(ctx context.Context, req *TenantCreateRequest, opts ...http.CallOption) (rsp *TenantCreateReply, err error)
	// Delete 删除租户
	Delete(ctx context.Context, req *TenantDeleteRequest, opts ...http.CallOption) (rsp *TenantDeleteReply, err error)
	// Get 获取租户详情
	Get(ctx context.Context, req *TenantGetRequest, opts ...http.CallOption) (rsp *TenantGetReply, err error)
	// List 获取租户列表
	List(ctx context.Context, req *TenantListRequest, opts ...http.CallOption) (rsp *TenantListReply, err error)
	// Update 更新租户
	Update(ctx context.Context, req *TenantUpdateRequest, opts ...http.CallOption) (rsp *TenantUpdateReply, err error)
}

type TenantHTTPClientImpl struct {
	cc *http.Client
}

func NewTenantHTTPClient(client *http.Client) TenantHTTPClient {
	return &TenantHTTPClientImpl{client}
}

// Create 创建租户
func (c *TenantHTTPClientImpl) Create(ctx context.Context, in *TenantCreateRequest, opts ...http.CallOption) (*TenantCreateReply, error) {
	var out TenantCreateReply
	pattern := "/api/v1/tenant"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTenantCreate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete 删除租户
func (c *TenantHTTPClientImpl) Delete(ctx context.Context, in *TenantDeleteRequest, opts ...http.CallOption) (*TenantDeleteReply, error) {
	var out TenantDeleteReply
	pattern := "/api/v1/tenant/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTenantDelete))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Get 获取租户详情
func (c *TenantHTTPClientImpl) Get(ctx context.Context, in *TenantGetRequest, opts ...http.CallOption) (*TenantGetReply, error) {
	var out TenantGetReply
	pattern := "/api/v1/tenant/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTenantGet))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// List 获取租户列表
func (c *TenantHTTPClientImpl) List(ctx context.Context, in *TenantListRequest, opts ...http.CallOption) (*TenantListReply, error) {
	var out TenantListReply
	pattern := "/api/v1/tenant/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTenantList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Update 更新租户
func (c *TenantHTTPClientImpl) Update(ctx context.Context, in *TenantUpdateRequest, opts ...http.CallOption) (*TenantUpdateReply, error) {
	var out TenantUpdateReply
	pattern := "/api/v1/tenant/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTenantUpdate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
